name: "Ansible Configure"
description: "Configure Ansible for Ansible operations"
inputs:
  #---------------------------------------------------------------------------------------------------------------------
  # Usage
  #---------------------------------------------------------------------------------------------------------------------
  # No Usage
  #---------------------------------------------------------------------------------------------------------------------
  # Common
  #---------------------------------------------------------------------------------------------------------------------
  # No Common
  #---------------------------------------------------------------------------------------------------------------------
  # Features
  #---------------------------------------------------------------------------------------------------------------------
  ansible-core-version:
    description: "Ansible Core Version"
    required: false
    default: "2.21.*"
  ansible-lint-version:
    description: "Ansible Lint Version"
    required: false
    default: "26.*"
  #---------------------------------------------------------------------------------------------------------------------
  # Platform
  #---------------------------------------------------------------------------------------------------------------------
  python-version:
    description: "Python Version"
    required: false
    default: "3.13"
  #---------------------------------------------------------------------------------------------------------------------
  # Registry
  #---------------------------------------------------------------------------------------------------------------------
  # No Registry
  #---------------------------------------------------------------------------------------------------------------------
  # Artifact
  #---------------------------------------------------------------------------------------------------------------------
  # No Artifact
  #---------------------------------------------------------------------------------------------------------------------
runs:
  using: "composite"
  steps:
    #-------------------------------------------------------------------------------------------------------------------
    # Setup Platform
    #-------------------------------------------------------------------------------------------------------------------
    - name: Set Up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
    #-------------------------------------------------------------------------------------------------------------------
    # Installing Package
    #-------------------------------------------------------------------------------------------------------------------
    - name: Install Ansible Packages
      shell: bash
      run: >-
        python -m pip install
        "ansible-core==${{ inputs.ansible-core-version }}"
        "ansible-lint==${{ inputs.ansible-lint-version }}"
