name: "Java Configure"
description: "Configure Java for Java Operations"
inputs:
  java-version:
    description: "Java Version"
    required: false
    default: 17.0.10
  gpg-sign:
    description: "GPG Sign"
    required: false
runs:
  using: "composite"
  steps:
  #---------------------------------------------------------------------------------------------------------------------
  # Setup Platform
  #---------------------------------------------------------------------------------------------------------------------
  - if: ${{ inputs.gpg-sign == 'false' }}
    name: Set Up Java
    uses: actions/setup-java@v3
    with:
      java-version: ${{ inputs.java-version }}
      distribution: adopt
      cache: maven
  - if: ${{ inputs.gpg-sign == 'true' }}
    name: Set Up Java
    uses: actions/setup-java@v3
    with:
      java-version: ${{ inputs.java-version }}
      distribution: adopt
      cache: maven
      gpg-private-key: ${{ env.GPG_PRIVATE_KEY }}
      gpg-passphrase: ${{ env.GPG_PASSPHRASE }}
    env:
      GPG_PRIVATE_KEY: ${{ env.GPG_PRIVATE_KEY }}
      GPG_PASSPHRASE: ${{ env.GPG_PASSPHRASE }}
  #---------------------------------------------------------------------------------------------------------------------
  # Cache Platform
  #---------------------------------------------------------------------------------------------------------------------
  - name: Cache Maven
    uses: actions/cache@v4
    with:
      path: ~/.m2
      key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
      restore-keys: ${{ runner.os }}-m2