name: "PHP Configure"
description: "Configure PHP for PHP Operations"
inputs:
  php-version:
    description: "PHP Version"
    required: false
    default: "8.1"
  php-extensions:
    description: "PHP Extensions"
    required: false
    default: "imagick, swoole"
  php-tools:
    description: "PHP Tools"
    required: false
    default: none
runs:
  using: "composite"
  steps:
  #---------------------------------------------------------------------------------------------------------------------
  # Setup Platform
  #---------------------------------------------------------------------------------------------------------------------
  - name: Set Up PHP
    uses: shivammathur/setup-php@v2
    with:
      php-version: ${{ inputs.php-version }}
      extensions: ${{ inputs.php-extensions }}
      tools: ${{ inputs.php-tools }}
      coverage: pcov
  #---------------------------------------------------------------------------------------------------------------------
  # Cache Platform
  #---------------------------------------------------------------------------------------------------------------------
  - id: cache-php
    name: Cache PHP Modules
    uses: shivammathur/cache-extensions@v1
    with:
      php-version:  ${{ inputs.php-version }}
      extensions: ${{ inputs.php-extensions }}
      key: ${{ runner.os }}-php-${{ hashFiles('**/composer-lock.json') }}
  - name: Cache PHP Modules
    uses: actions/cache@v4
    with:
      path: ${{ steps.cache-php.outputs.dir }}
      key: ${{ runner.os }}-php-${{ hashFiles('**/composer-lock.json') }}
      restore-keys: ${{ runner.os }}-php