name: "Git Configure"
description: "Configure Git for Git Operations"
inputs:
  #---------------------------------------------------------------------------------------------------------------------
  # Usage
  #---------------------------------------------------------------------------------------------------------------------
  user-mail:
    description: "Git Mail"
    required: true
    default: "actions@github.com"
  user-name:
    description: "Git Name"
    required: true
    default: "GitHub Actions"
  #---------------------------------------------------------------------------------------------------------------------
  # Common
  #---------------------------------------------------------------------------------------------------------------------
  # No Common
  #---------------------------------------------------------------------------------------------------------------------
  # Features
  #---------------------------------------------------------------------------------------------------------------------
  # No Features
  #---------------------------------------------------------------------------------------------------------------------
  # Platform
  #---------------------------------------------------------------------------------------------------------------------
  # No Platform
  #---------------------------------------------------------------------------------------------------------------------
  # Registry
  #---------------------------------------------------------------------------------------------------------------------
  # No Registry
  #---------------------------------------------------------------------------------------------------------------------
  # Artifact
  #---------------------------------------------------------------------------------------------------------------------
  # No Artifact
  #---------------------------------------------------------------------------------------------------------------------
outputs:
  #---------------------------------------------------------------------------------------------------------------------
  # Usage
  #---------------------------------------------------------------------------------------------------------------------
  git-mail:
    description: "Git Mail"
    value: ${{ steps.git-mail.outputs.git-mail }}
  git-user:
    description: "GIt Name"
    value: ${{ steps.git-user.outputs.git-user }}
runs:
  using: "composite"
  steps:
  #---------------------------------------------------------------------------------------------------------------------
  # Setup Git
  #---------------------------------------------------------------------------------------------------------------------
  - name: Configure Git Email
    shell: bash
    working-directory: .
    run: git config user.email "${{ inputs.user-mail }}"
  - name: Configure Git user
    shell: bash
    working-directory: .
    run: git config user.name "${{ inputs.user-name }}"
  #---------------------------------------------------------------------------------------------------------------------
  # Set Output
  #---------------------------------------------------------------------------------------------------------------------
  - id: git-mail
    name: Git Mail
    shell: bash
    working-directory: .
    run: echo "git-mail=${{ inputs.user-mail }}" >> $GITHUB_OUTPUT
  - id: git-user
    name: Git User
    shell: bash
    working-directory: .
    run: echo "git-user=${{ inputs.user-name }}" >> $GITHUB_OUTPUT
