name: "Build DotNet"
description: "Build DotNet"
inputs:
  dotnet-version:
    description: "DotNet Version"
    required: false
    default: "6"
runs:
  using: "composite"
  steps:
  #---------------------------------------------------------------------------------------------------------------------
  # Setup Platform
  #---------------------------------------------------------------------------------------------------------------------
  - name: Set Up Dotnet
    uses: actions/setup-dotnet@v3
    with:
      dotnet-version: ${{ inputs.dotnet-version }}