name: "Build DotNet"
description: "Build DotNet"
inputs:
  #---------------------------------------------------------------------------------------------------------------------
  # Usage
  #---------------------------------------------------------------------------------------------------------------------
  # No Usage
  #---------------------------------------------------------------------------------------------------------------------
  # Common
  #---------------------------------------------------------------------------------------------------------------------
  # No Common
  #---------------------------------------------------------------------------------------------------------------------
  # Features
  #---------------------------------------------------------------------------------------------------------------------
  # No Features
  #---------------------------------------------------------------------------------------------------------------------
  # Platform
  #---------------------------------------------------------------------------------------------------------------------
  dotnet-version:
    description: "DotNet Version"
    required: false
    default: "6"
  #---------------------------------------------------------------------------------------------------------------------
  # Registry
  #---------------------------------------------------------------------------------------------------------------------
  # No Registry
  #---------------------------------------------------------------------------------------------------------------------
  # Artifact
  #---------------------------------------------------------------------------------------------------------------------
  # No Artifact
  #---------------------------------------------------------------------------------------------------------------------
runs:
  using: "composite"
  steps:
  #---------------------------------------------------------------------------------------------------------------------
  # Setup Platform
  #---------------------------------------------------------------------------------------------------------------------
  - name: Set Up Dotnet
    uses: actions/setup-dotnet@v6
    with:
      dotnet-version: ${{ inputs.dotnet-version }}
