name: "Maven Get Version"
description: "Maven Get Version"
inputs:
  java-version:
    description: "Java Version"
    required: false
    default: 17.0.10
  checkout:
    description: "Checkout Repository"
    required: false
    default: "true"
  configure-java:
    description: "Configure Java"
    required: false
    default: "true"
outputs:
  versions:
    description: "Maven Get Version"
    value: ${{ steps.versions.outputs.version }}
runs:
  using: "composite"
  steps:
  #---------------------------------------------------------------------------------------------------------------------
  # Prepare Repository
  #---------------------------------------------------------------------------------------------------------------------
  - if: ${{ inputs.checkout == 'true' }}
    name: Prepare
    uses: actions/checkout@v3
  #---------------------------------------------------------------------------------------------------------------------
  # Setup Platform
  #---------------------------------------------------------------------------------------------------------------------
  - if: ${{ inputs.checkout == 'true' }}
    name: Configure Java
    uses: bayudwiyansatria/.github/actions/configure-java@master
    with:
      java-version: ${{ inputs.java-version }}
  #---------------------------------------------------------------------------------------------------------------------
  # Task
  #---------------------------------------------------------------------------------------------------------------------
  - name: Version
    id: versions
    shell: bash
    working-directory: .
    run: echo "version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_OUTPUT