name: "Helm Get Version"
description: "Helm Get Version"
inputs:
  checkout:
    description: "Checkout Repository"
    required: false
    default: "true"
  working-directory:
    description: "Working Directory"
    required: false
    default: "./charts"
outputs:
  version:
    description: "Helm Get Version"
    value: ${{ steps.versions.outputs.version }}
runs:
  using: "composite"
  steps:
  #---------------------------------------------------------------------------------------------------------------------
  # Prepare Repository
  #---------------------------------------------------------------------------------------------------------------------
  - if: ${{ inputs.checkout == 'true' }}
    name: Prepare
    uses: actions/checkout@v4
  #---------------------------------------------------------------------------------------------------------------------
  # Setup Platform
  #---------------------------------------------------------------------------------------------------------------------
  - name: Set up Helm
    uses: azure/setup-helm@v4
  #---------------------------------------------------------------------------------------------------------------------
  # Task
  #---------------------------------------------------------------------------------------------------------------------
  - name: Version
    id: versions
    shell: bash
    working-directory: ${{ inputs.working-directory }}
    run: echo "version=$(helm show chart . | grep "^version:" | awk '{print $2}')" >> $GITHUB_OUTPUT