name: "Helm Get Version"
description: "Helm Get Version"
inputs:
  #---------------------------------------------------------------------------------------------------------------------
  # Usage
  #---------------------------------------------------------------------------------------------------------------------
  # No Usage
  #---------------------------------------------------------------------------------------------------------------------
  # Common
  #---------------------------------------------------------------------------------------------------------------------
  working-directory:
    description: "Working Directory"
    required: false
    default: "./charts"
  #---------------------------------------------------------------------------------------------------------------------
  # Features
  #---------------------------------------------------------------------------------------------------------------------
  checkout:
    description: "Checkout Repository"
    required: false
    default: "true"
  #---------------------------------------------------------------------------------------------------------------------
  # Platform
  #---------------------------------------------------------------------------------------------------------------------
  # No Platform
  #---------------------------------------------------------------------------------------------------------------------
  # Registry
  #---------------------------------------------------------------------------------------------------------------------
  # No Registry
  #---------------------------------------------------------------------------------------------------------------------
  # Artifact
  #---------------------------------------------------------------------------------------------------------------------
  # No Artifact
  #---------------------------------------------------------------------------------------------------------------------
outputs:
  #---------------------------------------------------------------------------------------------------------------------
  # Version
  #---------------------------------------------------------------------------------------------------------------------
  version:
    description: "Helm Get Version"
    value: ${{ steps.versions.outputs.version }}
runs:
  using: "composite"
  steps:
  #---------------------------------------------------------------------------------------------------------------------
  # Prepare Repository
  #---------------------------------------------------------------------------------------------------------------------
  - if: ${{ inputs.checkout == 'true' }}
    name: Prepare
    uses: actions/checkout@v7
  #---------------------------------------------------------------------------------------------------------------------
  # Setup Platform
  #---------------------------------------------------------------------------------------------------------------------
  - name: Set up Helm
    uses: azure/setup-helm@v4
  #---------------------------------------------------------------------------------------------------------------------
  # Get Version
  #---------------------------------------------------------------------------------------------------------------------
  - name: Version
    id: versions
    shell: bash
    working-directory: ${{ inputs.working-directory }}
    run: echo "version=$(helm show chart . | grep "^version:" | awk '{print $2}')" >> $GITHUB_OUTPUT
