name: Build Gradle
on:
  workflow_call:
    inputs:
      #-----------------------------------------------------------------------------------------------------------------
      # Usage
      #-----------------------------------------------------------------------------------------------------------------
      SKIP_TEST:
        type: boolean
        required: false
        default: false
      #-----------------------------------------------------------------------------------------------------------------
      # Platform
      #-----------------------------------------------------------------------------------------------------------------
      OS_VERSION:
        type: string
        required: false
        default: ubuntu-24.04
      JAVA_VERSION:
        type: string
        required: false
        default: "11"
      #-----------------------------------------------------------------------------------------------------------------
      # Registry
      #-----------------------------------------------------------------------------------------------------------------  
      MAVEN_REGISTRY:
        type: string
        required: false
        default: maven.pkg.github.com
      #-----------------------------------------------------------------------------------------------------------------
      # Artifact
      #-----------------------------------------------------------------------------------------------------------------  
      ARTIFACT_NAME:
        type: string
        required: false
        default: target
      ARTIFACT_PATH:
        type: string
        required: false
        default: target
      ARTIFACT_RETENTION:
        type: string
        required: false
        default: "1"
    secrets:
      #-----------------------------------------------------------------------------------------------------------------
      # Registry
      #-----------------------------------------------------------------------------------------------------------------  
      MAVEN_USERNAME:
        required: true
      MAVEN_PASSWORD:
        required: true
jobs:
  #---------------------------------------------------------------------------------------------------------------------
  # Build
  #---------------------------------------------------------------------------------------------------------------------
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        java-version:
        - ${{ inputs.JAVA_VERSION }}
        os:
        - ${{ inputs.OS_VERSION }}
    steps:
    #-------------------------------------------------------------------------------------------------------------------
    # Prepare Repository
    #-------------------------------------------------------------------------------------------------------------------
    - name: Prepare
      uses: actions/checkout@v3
    #-------------------------------------------------------------------------------------------------------------------
    # Setup Platform
    #-------------------------------------------------------------------------------------------------------------------
    - name: Configure Java
      uses: bayudwiyansatria/.github/.github/actions/configure-java@master
      with:
        java-version: ${{ inputs.JAVA_VERSION }}
    #-------------------------------------------------------------------------------------------------------------------
    # Build Package
    #-------------------------------------------------------------------------------------------------------------------
    - name: Build Gradle Packages
      run: >-
        gradle
        -x
        bootJar
      env:
        MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
