name: Build Docker
on:
  workflow_call:
    inputs:
      #---------------------------------------------------------------------------------------------
      # Registry
      #---------------------------------------------------------------------------------------------
      DOCKER_REGISTRY:
        type: string
        required: false
        default: docker.io
      DOCKER_REPOSITORY:
        type: string
        required: true
      DOCKER_IMAGE_URL:
        type: string
        required: false
        default: docker.pkg.github.com/${{ github.repository }}
      DOCKER_IMAGE_TAG:
        type: string
        required: false
        default: ${{ github.sha }}
      DOCKER_FILE:
        type: string
        required: false
        default: Dockerfile
      DOCKER_CONTEXT:
        type: string
        required: false
        default: .
      #---------------------------------------------------------------------------------------------------------------------
      # Artifact
      #---------------------------------------------------------------------------------------------------------------------
      ARTIFACT_NAME:
        type: string
        required: false
        default: target
      ARTIFACT_PATH:
        type: string
        required: false
        default: target
    secrets:
      #---------------------------------------------------------------------------------------------
      # Registry
      #---------------------------------------------------------------------------------------------
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true
jobs:
  #-------------------------------------------------------------------------------------------------
  # Dockerized
  #-------------------------------------------------------------------------------------------------
  dockerized:
    name: Dockerized
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
        - ubuntu-24.04
    steps:
    #-----------------------------------------------------------------------------------------------
    # Checkout Repository
    #-----------------------------------------------------------------------------------------------
    - name: Prepare
      uses: actions/checkout@v4
    #-----------------------------------------------------------------------------------------------
    # Download Artifacts
    #-----------------------------------------------------------------------------------------------
    - name: Download Artifact
      uses: actions/download-artifact@v3
      with:
        name: ${{ inputs.ARTIFACT_NAME }}
        path: ${{ inputs.ARTIFACT_PATH }}
    #-----------------------------------------------------------------------------------------------
    # Registry Repository
    #-----------------------------------------------------------------------------------------------
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        registry: ${{ inputs.DOCKER_REGISTRY }}/${{ inputs.DOCKER_REPOSITORY }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    #-----------------------------------------------------------------------------------------------
    # Build
    #-----------------------------------------------------------------------------------------------
    - name: Build
      uses: docker/build-push-action@v4
      with:
        context: ${{ inputs.DOCKER_CONTEXT }}
        file: ${{ inputs.DOCKER_FILE }}
        push: true
        tags: ${{ inputs.DOCKER_IMAGE_URL }}:${{ inputs.DOCKER_IMAGE_TAG }}
