name: Dockerized
on:
  workflow_call:
    inputs:
      #---------------------------------------------------------------------------------------------
      # Registry
      #---------------------------------------------------------------------------------------------
      DOCKER_REGISTRY:
        type: string
        required: false
        default: docker.io
      DOCKER_REPOSITORY:
        type: string
        required: true
      DOCKER_FILE:
        type: string
        required: false
        default: Dockerfile
      DOCKER_CONTEXT:
        type: string
        required: false
        default: .
      #---------------------------------------------------------------------------------------------------------------------
      # Artifact
      #---------------------------------------------------------------------------------------------------------------------
      ARTIFACT_NAME:
        type: string
        required: false
        default: target
      ARTIFACT_PATH:
        type: string
        required: false
        default: target
    secrets:
      #---------------------------------------------------------------------------------------------
      # Registry
      #---------------------------------------------------------------------------------------------
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true
env:
  DOCKER: ${{ inputs.DOCKER_REGISTRY }}/${{ inputs.DOCKER_REPOSITORY }}
jobs:
  #-------------------------------------------------------------------------------------------------
  # Dockerized
  #-------------------------------------------------------------------------------------------------
  dockerized:
    name: Dockerized
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
        - ubuntu-latest
    steps:
    #-----------------------------------------------------------------------------------------------
    # Checkout Repository
    #-----------------------------------------------------------------------------------------------
    - name: Prepare
      uses: actions/checkout@v3
    #-----------------------------------------------------------------------------------------------
    # Download Artifacts
    #-----------------------------------------------------------------------------------------------
    - name: Download Artifact
      uses: actions/download-artifact@v3
      with:
        name: ${{ inputs.ARTIFACT_NAME }}
        path: ${{ inputs.ARTIFACT_PATH }}
    #-----------------------------------------------------------------------------------------------
    # Registry Repository
    #-----------------------------------------------------------------------------------------------
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        registry: ${{ env.DOCKER }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    #-----------------------------------------------------------------------------------------------
    # Get Short SHA
    #-----------------------------------------------------------------------------------------------
    - name: Get Short SHA
      id: git-short-sha
      shell: bash
      run: |
        short=$(git rev-parse --short ${{ github.sha }})
        echo "::set-output name=short_sha::$short"
    #-----------------------------------------------------------------------------------------------
    # Build
    #-----------------------------------------------------------------------------------------------
    - name: Build
      uses: docker/build-push-action@v4
      with:
        context: ${{ inputs.DOCKER_CONTEXT }}
        file: ${{ inputs.DOCKER_FILE }}
        push: true
        tags: ${{ env.DOCKER }}:${{ steps.git-short-sha.outputs.short_sha }}
