name: Build Docker
on:
  workflow_call:
    inputs:
      #-----------------------------------------------------------------------------------------------------------------
      # Usage
      #-----------------------------------------------------------------------------------------------------------------
      DOCKER_REPOSITORY:
        type: string
        required: false
        default: ${{ github.repository }}
      DOCKER_WORKING_DIR:
        type: string
        required: false
        default: .
      DOCKER_FILE:
        type: string
        required: false
        default: Dockerfile
      DOCKER_BUILD_ARG:
        type: string
        required: false
        default: null
      DOCKER_IMAGE_TAG:
        type: string
        required: false
        default: ${{ github.sha }}
      DOCKER_PUSH_ENABLED:
        type: boolean
        required: false
        default: false
      DOCKER_SBOM_ENABLED:
        type: boolean
        required: false
        default: true
      #-----------------------------------------------------------------------------------------------------------------
      # Platform
      #-----------------------------------------------------------------------------------------------------------------
      OS_VERSION:
        type: string
        required: false
        default: ubuntu-24.04
      DOCKER_VERSION:
        type: string
        required: false
        default: "20.10"
      #-----------------------------------------------------------------------------------------------------------------
      # Registry
      #-----------------------------------------------------------------------------------------------------------------
      DOCKER_REGISTRY:
        type: string
        required: false
        default: docker.pkg.github.com
      #-----------------------------------------------------------------------------------------------------------------
      # Artifact
      #-----------------------------------------------------------------------------------------------------------------
      ARTIFACT_ENABLED:
        type: boolean
        required: false
        default: true
      ARTIFACT_NAME:
        type: string
        required: false
        default: dist
      ARTIFACT_PATH:
        type: string
        required: false
        default: dist
    secrets:
      #-----------------------------------------------------------------------------------------------------------------
      # Registry
      #-----------------------------------------------------------------------------------------------------------------
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true
jobs:
  #---------------------------------------------------------------------------------------------------------------------
  # Dockerized
  #---------------------------------------------------------------------------------------------------------------------
  dockerized:
    name: Dockerized
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
        - ${{ inputs.OS_VERSION }}
    steps:
    #-------------------------------------------------------------------------------------------------------------------
    # Prepare Repository
    #-------------------------------------------------------------------------------------------------------------------
    - name: Prepare
      uses: actions/checkout@v3
    #-------------------------------------------------------------------------------------------------------------------
    # Download Artifacts
    #-------------------------------------------------------------------------------------------------------------------
    - name: Download Artifact
      if: ${{ inputs.ARTIFACT_ENABLED == true }}
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.ARTIFACT_NAME }}
        path: ${{ inputs.ARTIFACT_PATH }}
    #-------------------------------------------------------------------------------------------------------------------
    # Setup Platform
    #-------------------------------------------------------------------------------------------------------------------
    - name: Configure Docker
      uses: bayudwiyansatria/.github/actions/configure-docker@master
      with:
        docker-version: ${{ inputs.DOCKER_VERSION }}
        registry-url: ${{ inputs.DOCKER_REGISTRY }}
        registry-repository: ${{ inputs.DOCKER_REPOSITORY }}
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    #-------------------------------------------------------------------------------------------------------------------
    # Build Package
    #-------------------------------------------------------------------------------------------------------------------
    - name: Build
      run: docker build --build-arg ${{ inputs.DOCKER_BUILD_ARG }} -t ${{ inputs.DOCKER_REGISTRY }}/${{ inputs.DOCKER_REPOSITORY }}:${{ inputs.DOCKER_IMAGE_TAG }} -f ${{ inputs.DOCKER_FILE }} ${{ inputs.DOCKER_WORKING_DIR }}
    #-------------------------------------------------------------------------------------------------------------------
    # Push Package
    #-------------------------------------------------------------------------------------------------------------------
    - name: Push
      if: ${{ inputs.DOCKER_PUSH_ENABLED }}
      run: docker push ${{ inputs.DOCKER_REGISTRY }}/${{ inputs.DOCKER_REPOSITORY }}:${{ inputs.DOCKER_IMAGE_TAG }}
