name: Build Node
on:
  workflow_call:
    inputs:
      #---------------------------------------------------------------------------------------------------------------------
      # Platform
      #---------------------------------------------------------------------------------------------------------------------
      NODE_VERSION:
        type: string
        required: false
        default: "16"
      NODE_BUILD_COMMAND:
        type: string
        required: false
        default: npm run build --if-present
      NODE_WORKING_DIR:
        type: string
        required: false
        default: .
      #---------------------------------------------------------------------------------------------------------------------
      # Registry
      #---------------------------------------------------------------------------------------------------------------------
      NPM_REGISTRY:
        type: string
        required: false
        default: https://npm.pkg.github.com
      #---------------------------------------------------------------------------------------------------------------------
      # Artifact
      #---------------------------------------------------------------------------------------------------------------------
      ARTIFACT_NAME:
        type: string
        required: false
        default: lib
      ARTIFACT_PATH:
        type: string
        required: false
        default: lib
      ARTIFACT_RETENTION:
        type: string
        required: false
        default: "1"
    secrets:
      #---------------------------------------------------------------------------------------------------------------------
      # Registry
      #---------------------------------------------------------------------------------------------------------------------
      NPM_AUTH_TOKEN:
        required: true
jobs:
  #---------------------------------------------------------------------------------------------------------------------
  # Build
  #---------------------------------------------------------------------------------------------------------------------
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version:
        - ${{ inputs.NODE_VERSION }}
        os:
        - ubuntu-latest
    steps:
    # Prepare Repository
    - name: Prepare
      uses: actions/checkout@v3
    # Setup Node
    - name: Set Up Node
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: ${{ inputs.NPM_REGISTRY }}
        cache: npm
        always-auth: true
        check-latest: false
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
    # Cache NPM
    - name: Cache NPM Modules
      uses: actions/cache@v4
      with:
        path: ~/.npm
        key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
        restore-keys: ${{ runner.os }}-npm
    # Installing Package
    - name: Installing Node Packages
      run: npm ci
      working-directory: ${{ inputs.NODE_WORKING_DIR }}
    # Build
    - name: Build Node Packages
      run: ${{ inputs.NODE_BUILD_COMMAND }}
      working-directory: ${{ inputs.NODE_WORKING_DIR }}
    # Upload Artifact
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.ARTIFACT_NAME }}
        path: ${{ inputs.ARTIFACT_PATH }}
        retention-days: ${{ inputs.ARTIFACT_RETENTION }}
