name: Build Gradle
on:
  workflow_call:
    inputs:
      #---------------------------------------------------------------------------------------------------------------------
      # Platform
      #---------------------------------------------------------------------------------------------------------------------  
      JAVA_VERSION:
        type: string
        required: false
        default: "11"
      #---------------------------------------------------------------------------------------------------------------------
      # Registry
      #---------------------------------------------------------------------------------------------------------------------  
      MAVEN_REGISTRY:
        type: string
        required: false
        default: maven.pkg.github.com
      #---------------------------------------------------------------------------------------------------------------------
      # Artifact
      #---------------------------------------------------------------------------------------------------------------------  
      NAME:
        type: string
        required: false
        default: target
      PATH:
        type: string
        required: false
        default: target
      RETENTION:
        type: string
        required: false
        default: "1"
    secrets:
      #---------------------------------------------------------------------------------------------------------------------
      # Registry
      #---------------------------------------------------------------------------------------------------------------------  
      MAVEN_USERNAME:
        required: true
      MAVEN_PASSWORD:
        required: true
jobs:
  #---------------------------------------------------------------------------------------------------------------------
  # Build
  #---------------------------------------------------------------------------------------------------------------------
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        java-version:
        - ${{ inputs.JAVA_VERSION }}
        os:
        - ubuntu-latest
    steps:
    # Prepare Repository
    - name: Prepare
      uses: actions/checkout@v3
    # Setup Java
    - name: Set Up Java
      uses: actions/setup-java@v3
      with:
        java-version: ${{ matrix.java-version }}
        distribution: adopt
        cache: maven
    # Build
    - name: Build Gradle Packages
      run: >-
        gradle
        -x
        bootJar
      env:
        MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
