name: Build PHP
on:
  workflow_call:
    inputs:
      #-----------------------------------------------------------------------------------------------------------------
      # Usage
      #-----------------------------------------------------------------------------------------------------------------
      PHP_COMMAND:
        type: string
        required: false
        default: composer run build
      WORKING_DIR:
        type: string
        required: false
        default: .
      #-----------------------------------------------------------------------------------------------------------------
      # Platform
      #-----------------------------------------------------------------------------------------------------------------
      OS_VERSION:
        type: string
        required: false
        default: ubuntu-24.04
      PHP_VERSION:
        type: string
        required: false
        default: "8.4"
      NODE_VERSION:
        type: string
        required: false
        default: "16"
      #-----------------------------------------------------------------------------------------------------------------
      # Registry
      #-----------------------------------------------------------------------------------------------------------------
      # No PHP Registry
      #-----------------------------------------------------------------------------------------------------------------
      # Artifact
      #-----------------------------------------------------------------------------------------------------------------
      ARTIFACT_NAME:
        type: string
        required: false
        default: build
      ARTIFACT_PATH:
        type: string
        required: false
        default: .
      ARTIFACT_RETENTION:
        type: string
        required: false
        default: "1"
    secrets: {}
      #-----------------------------------------------------------------------------------------------------------------
      # Registry
      #-----------------------------------------------------------------------------------------------------------------
      # No PHP Registry
jobs:
  #---------------------------------------------------------------------------------------------------------------------
  # Build
  #---------------------------------------------------------------------------------------------------------------------
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        php-version:
        - ${{ inputs.PHP_VERSION }}
        os:
        - ${{ inputs.OS_VERSION }}
    steps:
    #-------------------------------------------------------------------------------------------------------------------
    # Prepare Repository
    #-------------------------------------------------------------------------------------------------------------------
    - name: Prepare
      uses: actions/checkout@v3
    #-------------------------------------------------------------------------------------------------------------------
    # Setup Platform
    #-------------------------------------------------------------------------------------------------------------------
    - name: Configure PHP
      uses: bayudwiyansatria/.github/actions/configure-php@master
      with:
        php-version: ${{ inputs.PHP_VERSION }}
    - name: Configure Node
      uses: bayudwiyansatria/.github/actions/configure-node@master
      with:
        node-version: ${{ inputs.NODE_VERSION }}
      env:
        NODE_AUTH_TOKEN: null
    #-------------------------------------------------------------------------------------------------------------------
    # Installing Package
    #-------------------------------------------------------------------------------------------------------------------
    - name: Install PHP Packages
      run: >-
        composer
        --prefer-dist
        --no-interaction
        --no-suggest
        install 
      working-directory: ${{ inputs.WORKING_DIR }}
    #-------------------------------------------------------------------------------------------------------------------
    # Build Package
    #-------------------------------------------------------------------------------------------------------------------
    - name: Build PHP Packages
      run: ${{ inputs.PHP_COMMAND }}
      working-directory: ${{ inputs.WORKING_DIR }}
    #-------------------------------------------------------------------------------------------------------------------
    # Upload Artifact
    #-------------------------------------------------------------------------------------------------------------------
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.ARTIFACT_NAME }}
        path: ${{ inputs.ARTIFACT_PATH }}
        retention-days: ${{ inputs.ARTIFACT_RETENTION }}
