name: Build Maven
on:
  workflow_call:
    inputs:
      #---------------------------------------------------------------------------------------------------------------------
      # Platform
      #---------------------------------------------------------------------------------------------------------------------  
      JAVA_VERSION:
        type: string
        required: false
        default: "11"
      #---------------------------------------------------------------------------------------------------------------------
      # Registry
      #---------------------------------------------------------------------------------------------------------------------  
      MAVEN_REGISTRY:
        type: string
        required: false
        default: maven.pkg.github.com
      MAVEN_SKIP_TEST:
        type: boolean
        required: false
        default: false
      #---------------------------------------------------------------------------------------------------------------------
      # Artifact
      #---------------------------------------------------------------------------------------------------------------------  
      ARTIFACT_NAME:
        type: string
        required: false
        default: target
      ARTIFACT_PATH:
        type: string
        required: false
        default: target
      ARTIFACT_RETENTION:
        type: string
        required: false
        default: "1"
    secrets:
      #---------------------------------------------------------------------------------------------------------------------
      # Registry
      #---------------------------------------------------------------------------------------------------------------------  
      MAVEN_USERNAME:
        required: true
      MAVEN_PASSWORD:
        required: true
jobs:
  #---------------------------------------------------------------------------------------------------------------------
  # Build
  #---------------------------------------------------------------------------------------------------------------------
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        java-version:
        - ${{ inputs.JAVA_VERSION }}
        os:
        - ubuntu-latest
    steps:
    # Prepare Repository
    - name: Prepare
      uses: actions/checkout@v3
    # Setup Java
    - name: Set Up Java
      uses: actions/setup-java@v3
      with:
        java-version: ${{ matrix.java-version }}
        distribution: adopt
        cache: maven
    # Cache Maven
    - name: Cache Maven Packages
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    # Build
    - name: Build Maven Packages
      if: ${{ inputs.MAVEN_SKIP_TEST == false }}
      run: >-
        mvn
        --no-transfer-progress
        --settings settings.xml
        --file pom.xml
        clean
        test
        package
      env:
        MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
    - name: Build Maven Packages with SkipTest
      if: ${{ inputs.MAVEN_SKIP_TEST == true }}
      run: >-
        mvn
        --no-transfer-progress
        --settings settings.xml
        --file pom.xml
        clean
        test
        package
        -DskipTests
      env:
        MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
    # Upload Artifact
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.ARTIFACT_NAME }}
        path: ${{ inputs.ARTIFACT_PATH }}
        retention-days: ${{ inputs.ARTIFACT_RETENTION }}
