name: Build Docker
on:
  workflow_call:
    inputs:
      #-----------------------------------------------------------------------------------------------------------------
      # Platform
      #-----------------------------------------------------------------------------------------------------------------
      DOCKER_VERSION:
        type: string
        required: false
        default: "20.10"
      DOCKER_BUILD_COMMAND:
        type: string
        required: false
        default: docker build
      DOCKER_WORKING_DIR:
        type: string
        required: false
        default: .
      DOCKER_FILE:
        type: string
        required: false
        default: Dockerfile
      DOCKER_REPOSITORY:
        type: string
        required: false
        default: ${{ github.repository }}
      DOCKER_IMAGE_TAG:
        type: string
        required: false
        default: ${{ github.sha }}
      #-----------------------------------------------------------------------------------------------------------------
      # Registry
      #-----------------------------------------------------------------------------------------------------------------
      DOCKER_REGISTRY:
        type: string
        required: false
        default: docker.pkg.github.com
      #-----------------------------------------------------------------------------------------------------------------
      # Artifact
      #-----------------------------------------------------------------------------------------------------------------
      BUILD_ARTIFACT_NAME:
        type: string
        required: false
        default: target
      BUILD_ARTIFACT_PATH:
        type: string
        required: false
        default: target
    secrets:
      #-----------------------------------------------------------------------------------------------------------------
      # Registry
      #-----------------------------------------------------------------------------------------------------------------
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true
jobs:
  #---------------------------------------------------------------------------------------------------------------------
  # Dockerized
  #---------------------------------------------------------------------------------------------------------------------
  dockerized:
    name: Dockerized
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
        - ubuntu-24.04
    steps:
    #-------------------------------------------------------------------------------------------------------------------
    # Prepare Repository
    #-------------------------------------------------------------------------------------------------------------------
    - name: Prepare
      uses: actions/checkout@v3
    #-------------------------------------------------------------------------------------------------------------------
    # Download Artifacts
    #-------------------------------------------------------------------------------------------------------------------
    - name: Download Artifact
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.BUILD_ARTIFACT_NAME }}
        path: ${{ inputs.BUILD_ARTIFACT_PATH }}
    #-------------------------------------------------------------------------------------------------------------------
    # Setup Platform
    #-------------------------------------------------------------------------------------------------------------------
    - name: Configure Docker
      uses: bayudwiyansatria/.github/.github/actions/configure-docker@master
      with:
        docker-version: ${{ inputs.DOCKER_VERSION }}
        registry-url: ${{ inputs.DOCKER_REGISTRY }}
        registry-repository: ${{ inputs.DOCKER_REPOSITORY }}
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    #-------------------------------------------------------------------------------------------------------------------
    # Build Package
    #-------------------------------------------------------------------------------------------------------------------
    - name: Build
      uses: docker/build-push-action@v6
      with:
        context: ${{ inputs.DOCKER_WORKING_DIR }}
        file: ${{ inputs.DOCKER_FILE }}
        push: true
        tags: ${{ inputs.DOCKER_REGISTRY }}/${{ inputs.DOCKER_REPOSITORY }}:${{ inputs.DOCKER_IMAGE_TAG }}
