name: Build Java
on:
  workflow_call:
    inputs:
      #---------------------------------------------------------------------------------------------------------------------
      # Platform
      #---------------------------------------------------------------------------------------------------------------------  
      JAVA_VERSION:
        required: true
        default: 11
        type: choice
        options:
        - 11
      #---------------------------------------------------------------------------------------------------------------------
      # Registry
      #---------------------------------------------------------------------------------------------------------------------  
      MAVEN_REGISTRY:
        type: string
        required: false
        default: maven.pkg.github.com
      #---------------------------------------------------------------------------------------------------------------------
      # Artifact
      #---------------------------------------------------------------------------------------------------------------------  
      NAME:
        type: string
        required: false
        default: target
      PATH:
        type: string
        required: false
        default: target
      RETENTION:
        type: integer
        required: false
        default: 1
    secrets:
      #---------------------------------------------------------------------------------------------------------------------
      # Registry
      #---------------------------------------------------------------------------------------------------------------------  
      MAVEN_USERNAME:
        required: true
      MAVEN_PASSWORD:
        required: true
jobs:
  #---------------------------------------------------------------------------------------------------------------------
  # Build
  #---------------------------------------------------------------------------------------------------------------------
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        java-version:
        - ${{ inputs.JAVA_VERSION }}
        os:
        - ubuntu-24.04
    steps:
    # Prepare Repository
    - name: Prepare
      uses: actions/checkout@v3
    # Setup Java
    - name: Build Maven Packages
      uses: ./workflows/build-java-maven.yaml
      with:
        NAME: ${{ inputs.NAME }}
        PATH: ${{ inputs.PATH }}
        RETENTION: ${{ inputs.RETENTION }}
        JAVA_VERSION: ${{ inputs.JAVA_VERSION }}
        MAVEN_REGISTRY: https://maven.pkg.github.com
      secrets:
        MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
    # Build
    - name: Build Gradle Packages
      uses: ./workflows/build-java-gradle.yaml
      with:
        NAME: ${{ inputs.NAME }}
        PATH: ${{ inputs.PATH }}
        RETENTION: ${{ inputs.RETENTION }}
        JAVA_VERSION: ${{ inputs.JAVA_VERSION }}
        MAVEN_REGISTRY: https://maven.pkg.github.com
      secrets:
        MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
