name: Build Dotnet
on:
  workflow_call:
    inputs:
      #---------------------------------------------------------------------------------------------------------------------
      # Platform
      #---------------------------------------------------------------------------------------------------------------------
      DOTNET_VERSION:
        type: string
        required: false
        default: "6"
      #---------------------------------------------------------------------------------------------------------------------
      # Registry
      #---------------------------------------------------------------------------------------------------------------------
      DOTNET_REGISTRY:
        type: string
        required: false
        default: nuget.pkg.github.com
      #---------------------------------------------------------------------------------------------------------------------
      # Artifact
      #---------------------------------------------------------------------------------------------------------------------
      NAME:
        type: string
        required: true
    secrets:
      #---------------------------------------------------------------------------------------------------------------------
      # Registry
      #---------------------------------------------------------------------------------------------------------------------
      DOTNET_AUTH_TOKEN:
        required: true
jobs:
  #---------------------------------------------------------------------------------------------------------------------
  # Build
  #---------------------------------------------------------------------------------------------------------------------
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        dotnet-version:
          - ${{ inputs.DOTNET_VERSION }}
        os:
          - ubuntu-24.04
    steps:
      # Prepare Repository
      - name: Prepare
        uses: actions/checkout@v3
      # Setup Dotnet
      - name: Set Up Dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      # Build
      - name: Build Dotnet Packages
        run: >-
          dotnet
          build
          --configuration Release
          {{ inputs.NAME }}.csproj
