name: Build Docker
on:
  workflow_call:
    inputs:
      #-----------------------------------------------------------------------------------------------------------------
      # Usage
      #-----------------------------------------------------------------------------------------------------------------
      HELM_REPOSITORY:
        type: string
        required: false
        default: ${{ github.repository }}
      HELM_CHART_NAME:
        type: string
        required: false
        default: ${{ github.event.repository.name }}
      #-----------------------------------------------------------------------------------------------------------------
      # Common
      #-----------------------------------------------------------------------------------------------------------------
      WORKING_DIR:
        type: string
        required: false
        default: ./charts
      #-----------------------------------------------------------------------------------------------------------------
      # Features
      #-----------------------------------------------------------------------------------------------------------------
      # No Features
      #-----------------------------------------------------------------------------------------------------------------
      # Platform
      #-----------------------------------------------------------------------------------------------------------------
      OS_VERSION:
        type: string
        required: false
        default: ubuntu-24.04
      #-----------------------------------------------------------------------------------------------------------------
      # Registry
      #-----------------------------------------------------------------------------------------------------------------
      # No Registry
      #-----------------------------------------------------------------------------------------------------------------
      ARTIFACT_NAME:
        type: string
        required: false
        default: ${{ github.event.repository.name }}-0.1.0.tgz
      ARTIFACT_PATH:
        type: string
        required: false
        default: ${{ github.event.repository.name }}-0.1.0.tgz
      ARTIFACT_RETENTION:
        type: string
        required: false
        default: "1"
      #-----------------------------------------------------------------------------------------------------------------
    secrets:
      #-----------------------------------------------------------------------------------------------------------------
      # Registry
      #-----------------------------------------------------------------------------------------------------------------
      HELM_AUTH_TOKEN:
        required: true
jobs:
  #---------------------------------------------------------------------------------------------------------------------
  # Build
  #---------------------------------------------------------------------------------------------------------------------
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
        - ${{ inputs.OS_VERSION }}
    steps:
    #-------------------------------------------------------------------------------------------------------------------
    # Prepare Repository
    #-------------------------------------------------------------------------------------------------------------------
    - name: Prepare
      uses: actions/checkout@v4
    #-------------------------------------------------------------------------------------------------------------------
    # Setup Platform
    #-------------------------------------------------------------------------------------------------------------------
    - name: Set up Helm
      uses: azure/setup-helm@v4
    #-------------------------------------------------------------------------------------------------------------------
    # Build Package
    #-------------------------------------------------------------------------------------------------------------------
    - name: Package Helm Chart
      run: helm package ${{ inputs.WORKING_DIR }}/${{ inputs.HELM_CHART_NAME }}
    #-------------------------------------------------------------------------------------------------------------------
    # Helm Versions
    #-------------------------------------------------------------------------------------------------------------------
    - name: Get Helm Version
      id: versions
      uses: bayudwiyansatria/.github/actions/helm-get-version@master
      with:
        checkout: false
        working-directory: ${{ inputs.WORKING_DIR }}/${{ inputs.HELM_CHART_NAME }}
    #-------------------------------------------------------------------------------------------------------------------
    # Upload Artifact
    #-------------------------------------------------------------------------------------------------------------------
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.HELM_CHART_NAME }}-${{ steps.versions.outputs.version }}.tgz
        path: ${{ inputs.HELM_CHART_NAME }}-${{ steps.versions.outputs.version }}.tgz
        retention-days: ${{ inputs.ARTIFACT_RETENTION }}