name: Deploy Node
on:
  workflow_call:
    inputs:
      #---------------------------------------------------------------------------------------------------------------------
      # Version
      #---------------------------------------------------------------------------------------------------------------------
      MAJOR_VERSION:
        type: string
        required: false
        default: "0"
      MINOR_VERSION:
        type: string
        required: false
        default: "0"
      INCREMENTAL_VERSION:
        type: string
        required: false
        default: "0"
      #---------------------------------------------------------------------------------------------------------------------
      # Platform
      #---------------------------------------------------------------------------------------------------------------------
      NODE_VERSION:
        type: string
        required: false
        default: "16"
      #---------------------------------------------------------------------------------------------------------------------
      # Registry
      #---------------------------------------------------------------------------------------------------------------------
      NPM_REGISTRY:
        type: string
        required: false
        default: https://npm.pkg.github.com
      #---------------------------------------------------------------------------------------------------------------------
      # Artifact
      #---------------------------------------------------------------------------------------------------------------------
      ARTIFACT_NAME:
        type: string
        required: false
        default: lib
      ARTIFACT_PATH:
        type: string
        required: false
        default: lib
    secrets:
      #---------------------------------------------------------------------------------------------------------------------
      # Registry
      #---------------------------------------------------------------------------------------------------------------------
      NPM_AUTH_TOKEN:
        required: true
      GITHUB_PAT:
        required: true
env:
  tag_name: ${{ inputs.MAJOR_VERSION }}.${{ inputs.MINOR_VERSION }}.${{ inputs.INCREMENTAL_VERSION }}
jobs:
  release:
    name: Release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version:
        - ${{ inputs.NODE_VERSION }}
        os:
        - ubuntu-24.04
    steps:
    #-------------------------------------------------------------------------------------------------------------------------
    # Prepare Repository
    #-------------------------------------------------------------------------------------------------------------------------
    - name: Prepare
      uses: actions/checkout@v3
    #-------------------------------------------------------------------------------------------------------------------------
    # Download Artifact
    #-------------------------------------------------------------------------------------------------------------------------
    - name: Download Artifacts
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.ARTIFACT_NAME }}
        path: ${{ inputs.ARTIFACT_PATH }}
    #-------------------------------------------------------------------------------------------------------------------------
    # Setup Platform
    #-------------------------------------------------------------------------------------------------------------------------
    - name: Set Up Node
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: ${{ inputs.NPM_REGISTRY }}
        cache: npm
        always-auth: true
        check-latest: false
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
    #-------------------------------------------------------------------------------------------------------------------------
    # Setup Git
    #-------------------------------------------------------------------------------------------------------------------------
    - name: Configure Git
      uses: bayudwiyansatria/.github/.github/actions/git-configure@master
    - name: Tag Git
      uses: bayudwiyansatria/.github/.github/actions/git-tag@master
      with:
        tag: ${{ env.tag_name }}
        git-token: ${{ secrets.GITHUB_PAT }}
    #-------------------------------------------------------------------------------------------------------------------------
    # Publish Package
    #-------------------------------------------------------------------------------------------------------------------------
    - name: Release
      run: npm publish --if-present