name: Deploy Azure
on:
  workflow_call:
    inputs:
      #-----------------------------------------------------------------------------------------------------------------
      # Deployment
      #-----------------------------------------------------------------------------------------------------------------
      ENVIRONMENT:
        type: string
        required: false
        default: development
      #-----------------------------------------------------------------------------------------------------------------
      # Artifact
      #-----------------------------------------------------------------------------------------------------------------
      ARTIFACT_NAME:
        type: string
        required: false
        default: target
      ARTIFACT_PATH:
        type: string
        required: false
        default: target
      #-----------------------------------------------------------------------------------------------------------------
      # Azure
      #-----------------------------------------------------------------------------------------------------------------
      AZURE_TYPE:
        type: string
        required: true
      AZURE_APP_NAME:
        type: string
        required: true
      AZURE_APP_SLOT:
        type: string
        required: false
        default: production
      AZURE_ARTIFACT:
        type: string
        required: true
      AZURE_IDENTITY:
        type: string
        required: false
        default: IDENTITY
    secrets:
      #-----------------------------------------------------------------------------------------------------------------
      # Registry
      #-----------------------------------------------------------------------------------------------------------------
      AZURE_TENANT_ID:
        required: false
      AZURE_SUBSCRIPTION_ID:
        required: false
      AZURE_CLIENT_ID:
        required: false
      AZURE_CREDENTIALS:
        required: false
permissions:
  id-token: write
  contents: read
jobs:
  #---------------------------------------------------------------------------------------------------------------------
  # Deploy
  #---------------------------------------------------------------------------------------------------------------------
  deploy:
    name: Deploy
    runs-on: ${{ matrix.os }}
    environment: 
      name: ${{ inputs.ENVIRONMENT }}
      url: ${{ steps.webapp.outputs.webapp-url }}
    strategy:
      matrix:
        os:
        - ubuntu-24.04
    steps:
    #-------------------------------------------------------------------------------------------------------------------
    # Download Artifact
    #-------------------------------------------------------------------------------------------------------------------
    - name: Download Artifact
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.ARTIFACT_NAME }}
        path: ${{ inputs.ARTIFACT_PATH }}
    #-------------------------------------------------------------------------------------------------------------------
    # Setup Platform
    #-------------------------------------------------------------------------------------------------------------------
    - name: Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        auth-type: ${{ inputs.AZURE_IDENTITY }}
        enable-AzPSSession: true
    - name: Deploy to Azure Web App
      id: webapp
      if: ${{ inputs.AZURE_TYPE == 'WebApp' }}
      uses: azure/webapps-deploy@v3
      with:
        app-name: ${{ inputs.AZURE_APP_NAME }}
        slot-name: ${{ inputs.AZURE_APP_SLOT }}
        package: ${{ inputs.AZURE_ARTIFACT }}
