name: Deploy Node
on:
  workflow_call:
    inputs:
      #---------------------------------------------------------------------------------------------------------------------
      # Version
      #---------------------------------------------------------------------------------------------------------------------
      MAJOR_VERSION:
        type: string
        required: false
        default: "0"
      MINOR_VERSION:
        type: string
        required: false
        default: "0"
      INCREMENTAL_VERSION:
        type: string
        required: false
        default: "0"
      #---------------------------------------------------------------------------------------------------------------------
      # Platform
      #---------------------------------------------------------------------------------------------------------------------
      NODE_VERSION:
        type: string
        required: false
        default: "16"
      #---------------------------------------------------------------------------------------------------------------------
      # Registry
      #---------------------------------------------------------------------------------------------------------------------
      NPM_REGISTRY:
        type: string
        required: false
        default: https://npm.pkg.github.com
      #---------------------------------------------------------------------------------------------------------------------
      # Artifact
      #---------------------------------------------------------------------------------------------------------------------
      ARTIFACT_NAME:
        type: string
        required: false
        default: lib
      ARTIFACT_PATH:
        type: string
        required: false
        default: lib
    secrets:
      #---------------------------------------------------------------------------------------------------------------------
      # Registry
      #---------------------------------------------------------------------------------------------------------------------
      NPM_AUTH_TOKEN:
        required: true
      GITHUB_PAT:
        required: true
env:
  tag_name: ${{ inputs.MAJOR_VERSION }}.${{ inputs.MINOR_VERSION }}.${{ inputs.INCREMENTAL_VERSION }}
jobs:
  release:
    name: Release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version:
        - ${{ inputs.NODE_VERSION }}
        os:
        - ubuntu-latest
    steps:
    # Prepare Repository
    - name: Prepare
      uses: actions/checkout@v3
    # Download Artifact
    - name: Download Artifacts
      uses: actions/download-artifact@v3
      with:
        name: ${{ inputs.ARTIFACT_NAME }}
        path: ${{ inputs.ARTIFACT_PATH }}
    # Setup Node
    - name: Set Up Node
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: ${{ inputs.NPM_REGISTRY }}
        cache: npm
        always-auth: true
        check-latest: false
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
    # Setup Git User
    - name: Configure Git user
      run: |
        git config user.email "actions@github.com"
        git config user.name "GitHub Actions"
    # Tag for Release
    - name: Tag Release
      run: |
        git tag ${{ env.tag_name }}
        git push origin ${{ env.tag_name }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_PAT }}
    # Release
    - name: Release
      run: npm publish --if-present