name: Deploy to Cloudflare
on:
  workflow_call:
    inputs:
      #-----------------------------------------------------------------------------------------------------------------
      # Usage
      #-----------------------------------------------------------------------------------------------------------------
      ENVIRONMENT:
        type: string
        required: false
        default: development
      WRANGLER_COMMAND:
        type: string
        required: false
        default: deploy lib/worker.mjs --name ${{ github.event.repository.name }}
      #-----------------------------------------------------------------------------------------------------------------
      # Common
      #-----------------------------------------------------------------------------------------------------------------
      WORKING_DIR:
        type: string
        required: false
        default: .
      #-----------------------------------------------------------------------------------------------------------------
      # Features
      #-----------------------------------------------------------------------------------------------------------------
      # No Features
      #-----------------------------------------------------------------------------------------------------------------
      # Platform
      #-----------------------------------------------------------------------------------------------------------------
      OS_VERSION:
        type: string
        required: false
        default: ubuntu-24.04
      WRANGLER_VERSION:
        type: string
        required: false
        default: "3.91.0"
      #-----------------------------------------------------------------------------------------------------------------
      # Artifact
      #-----------------------------------------------------------------------------------------------------------------
      ARTIFACT_NAME:
        type: string
        required: false
        default: lib
      ARTIFACT_PATH:
        type: string
        required: false
        default: lib
    secrets:
      #-----------------------------------------------------------------------------------------------------------------
      # Platform
      #-----------------------------------------------------------------------------------------------------------------
      CLOUDFLARE_ACCOUNT_ID:
        required: true
      CLOUDFLARE_API_TOKEN:
        required: true
permissions:
  id-token: write
  contents: read
jobs:
  #---------------------------------------------------------------------------------------------------------------------
  # Deploy
  #---------------------------------------------------------------------------------------------------------------------
  deploy:
    name: Deploy
    runs-on: ${{ matrix.os }}
    environment: 
      name: ${{ inputs.ENVIRONMENT }}
    strategy:
      matrix:
        os:
        - ${{ inputs.OS_VERSION }}
    steps:
    #-------------------------------------------------------------------------------------------------------------------
    # Download Artifact
    #-------------------------------------------------------------------------------------------------------------------
    - name: Download Artifact
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.ARTIFACT_NAME }}
        path: ${{ inputs.ARTIFACT_PATH }}
    - name: Get Compatibility
      id: compatibility
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      working-directory: ${{ inputs.WORKING_DIR }}
    #-------------------------------------------------------------------------------------------------------------------
    # Publish Package
    #-------------------------------------------------------------------------------------------------------------------
    - name: Deploy to Cloudflare Worker
      id: webapp
      uses: cloudflare/wrangler-action@v3
      with:
        wranglerVersion: ${{ inputs.WRANGLER_VERSION}}
        apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        command: ${{ inputs.WRANGLER_COMMAND }} --compatibility-date ${{ steps.compatibility.outputs.date }}