name: Deploy Node
on:
  workflow_call:
    inputs:
      #-----------------------------------------------------------------------------------------------------------------
      # Version
      #-----------------------------------------------------------------------------------------------------------------
      MAJOR_VERSION:
        type: string
        required: false
        default: "0"
      MINOR_VERSION:
        type: string
        required: false
        default: "0"
      INCREMENTAL_VERSION:
        type: string
        required: false
        default: "0"
      #-----------------------------------------------------------------------------------------------------------------
      # Usage
      #-----------------------------------------------------------------------------------------------------------------
      NODE_COMMAND:
        type: string
        required: false
        default: npm publish --if-present
      #-----------------------------------------------------------------------------------------------------------------
      # Common
      #-----------------------------------------------------------------------------------------------------------------
      WORKING_DIR:
        type: string
        required: false
        default: .
      #-----------------------------------------------------------------------------------------------------------------
      # Features
      #-----------------------------------------------------------------------------------------------------------------
      # No Features
      #-----------------------------------------------------------------------------------------------------------------
      # Platform
      #-----------------------------------------------------------------------------------------------------------------
      OS_VERSION:
        type: string
        required: false
        default: ubuntu-24.04
      NODE_VERSION:
        type: string
        required: false
        default: "16"
      #-----------------------------------------------------------------------------------------------------------------
      # Registry
      #-----------------------------------------------------------------------------------------------------------------
      NPM_REGISTRY:
        type: string
        required: false
        default: npm.pkg.github.com
      #-----------------------------------------------------------------------------------------------------------------
      # Artifact
      #-----------------------------------------------------------------------------------------------------------------
      ARTIFACT_NAME:
        type: string
        required: false
        default: lib
      ARTIFACT_PATH:
        type: string
        required: false
        default: lib
    secrets:
      #-----------------------------------------------------------------------------------------------------------------
      # Registry
      #-----------------------------------------------------------------------------------------------------------------
      NPM_AUTH_TOKEN:
        required: true
      GITHUB_PAT:
        required: true
env:
  tag_name: ${{ inputs.MAJOR_VERSION }}.${{ inputs.MINOR_VERSION }}.${{ inputs.INCREMENTAL_VERSION }}
jobs:
  release:
    name: Release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version:
        - ${{ inputs.NODE_VERSION }}
        os:
        - ${{ inputs.OS_VERSION }}
    steps:
    #-------------------------------------------------------------------------------------------------------------------
    # Prepare Repository
    #-------------------------------------------------------------------------------------------------------------------
    - name: Prepare
      uses: actions/checkout@v4
    #-------------------------------------------------------------------------------------------------------------------
    # Download Artifact
    #-------------------------------------------------------------------------------------------------------------------
    - name: Download Artifacts
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.ARTIFACT_NAME }}
        path: ${{ inputs.ARTIFACT_PATH }}
    #-------------------------------------------------------------------------------------------------------------------
    # Setup Platform
    #-------------------------------------------------------------------------------------------------------------------
    - name: Configure Node
      uses: bayudwiyansatria/.github/actions/configure-node@master
      with:
        node-version: ${{ inputs.NODE_VERSION }}
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
    #-------------------------------------------------------------------------------------------------------------------
    # Setup Git
    #-------------------------------------------------------------------------------------------------------------------
    - name: Configure Git
      uses: bayudwiyansatria/.github/actions/git-configure@master
    - name: Tag Git
      uses: bayudwiyansatria/.github/actions/git-tag@master
      with:
        tag: ${{ env.tag_name }}
        git-token: ${{ secrets.GITHUB_PAT }}
    #-------------------------------------------------------------------------------------------------------------------
    # Publish Package
    #-------------------------------------------------------------------------------------------------------------------
    - name: Release
      run: ${{ inputs.NODE_COMMAND }}
