name: Dockerized
on:
  workflow_call:
    inputs:
      IMAGE_TAG:
        type: string
        required: true
      DEPLOY_TAG:
        type: string
        required: true
jobs:
  #-------------------------------------------------------------------------------------------------
  # Dockerized
  #-------------------------------------------------------------------------------------------------
  dockerized:
    name: Dockerized
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
        - ubuntu-latest
    steps:
    #-----------------------------------------------------------------------------------------------
    # Checkout Repository
    #-----------------------------------------------------------------------------------------------
    - name: Prepare
      uses: actions/checkout@v3
    #-----------------------------------------------------------------------------------------------
    # Registry Repository
    #-----------------------------------------------------------------------------------------------
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        registry: ghcr.io/${{ github.repository }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    #-----------------------------------------------------------------------------------------------
    # Re-tag
    #-----------------------------------------------------------------------------------------------
    - name: Re-tag Artifact
      if: ${{ github.event_name != 'workflow_dispatch' }}
      run: |
        docker pull ${{ inputs.IMAGE_TAG }}
        docker tag ${{ inputs.IMAGE_TAG }} ${{ inputs.DEPLOY_TAG }}
        docker push ${{ inputs.DEPLOY_TAG }}
