name: Deploy Docker
on:
  workflow_call:
    inputs:
      #-----------------------------------------------------------------------------------------------------------------
      # Usage
      #-----------------------------------------------------------------------------------------------------------------
      ENVIRONMENT:
        type: string
        required: false
        default: development
      DOCKER_TAG_ENVIRONMENT_ENABLED:
          type: boolean
          required: false
          default: false
      DOCKER_TAG_LATEST_ENABLED:
        type: boolean
        required: false
        default: false
      DOCKER_TAG_SHORT_SHA_ENABLED:
        type: boolean
        required: false
        default: false
      DOCKER_TAG_REF_ENABLED:
        type: boolean
        required: false
        default: false
      DOCKER_REPOSITORY:
        type: string
        required: false
        default: ${{ inputs.DOCKER_REGISTRY }}/${{ github.repository }}
      DOCKER_WORKING_DIR:
        type: string
        required: false
        default: .
      DOCKER_IMAGE_TAG:
        type: string
        required: false
        default: ${{ github.sha }}
      DOCKER_TAG_URL:
        type: string
        required: false
        default: docker.pkg.github.com/${{ github.repository }}
      DOCKER_DEPLOY_TAG:
        type: string
        required: false
      #-----------------------------------------------------------------------------------------------------------------
      # Platform
      #-----------------------------------------------------------------------------------------------------------------
      OS_VERSION:
        type: string
        required: false
        default: ubuntu-24.04
      DOCKER_VERSION:
        type: string
        required: false
        default: "20.10"
      #-----------------------------------------------------------------------------------------------------------------
      # Registry
      #-----------------------------------------------------------------------------------------------------------------
      DOCKER_REGISTRY:
        type: string
        required: false
        default: docker.io
      #-----------------------------------------------------------------------------------------------------------------
      # Artifact
      #-----------------------------------------------------------------------------------------------------------------
    secrets:
      #-----------------------------------------------------------------------------------------------------------------
      # Registry
      #-----------------------------------------------------------------------------------------------------------------
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true
jobs:
  #---------------------------------------------------------------------------------------------------------------------
  # Dockerized
  #---------------------------------------------------------------------------------------------------------------------
  dockerized:
    name: Dockerized
    environment: ${{ inputs.ENVIRONMENT }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
        - ${{ inputs.OS_VERSION }}
    steps:
    #-------------------------------------------------------------------------------------------------------------------
    # Prepare Repository
    #-------------------------------------------------------------------------------------------------------------------
    - name: Prepare
      uses: actions/checkout@v3
    #-------------------------------------------------------------------------------------------------------------------
    # Setup Platform
    #-------------------------------------------------------------------------------------------------------------------
    - name: Configure Docker
      uses: bayudwiyansatria/.github/actions/configure-docker@master
      with:
        docker-version: ${{ inputs.DOCKER_VERSION }}
        registry-url: ${{ inputs.DOCKER_REGISTRY }}
        registry-repository: ${{ inputs.DOCKER_REPOSITORY }}
    #-------------------------------------------------------------------------------------------------------------------
    # Get Short SHA
    #-------------------------------------------------------------------------------------------------------------------
    - name: Get Short SHA
      id: git-short-sha
      shell: bash
      working-directory: ${{ inputs.DOCKER_WORKING_DIR }}
      run: |
        short=$(git rev-parse --short ${{ github.sha }})
        echo "short_sha=$short" >> $GITHUB_OUTPUT
    #-------------------------------------------------------------------------------------------------------------------
    # Get Branch / Tag Name
    #-------------------------------------------------------------------------------------------------------------------
    - name: Get Branch or Tag Name
      id: git-ref
      shell: bash
      working-directory: ${{ inputs.DOCKER_WORKING_DIR }}
      run: |
        tag=$GITHUB_REF_NAME
        echo "tag=$tag" >> $GITHUB_OUTPUT
    #-------------------------------------------------------------------------------------------------------------------
    # Re-tag
    #-------------------------------------------------------------------------------------------------------------------
    - name: Re-tag Artifact
      if: ${{ inputs.DOCKER_DEPLOY_TAG != '' }}
      working-directory: ${{ inputs.DOCKER_WORKING_DIR }}
      run: |
        docker pull ${{ inputs.DOCKER_TAG_URL }}:${{ inputs.DOCKER_IMAGE_TAG }}
        docker tag ${{ inputs.DOCKER_TAG_URL }}:${{ inputs.DOCKER_IMAGE_TAG }} ${{ inputs.DOCKER_TAG_URL }}:${{ inputs.DOCKER_DEPLOY_TAG }}
        docker push ${{ inputs.DOCKER_TAG_URL }}:${{ inputs.DOCKER_DEPLOY_TAG }}
    - name: Re-tag Artifact with Environment
      if: ${{ inputs.DOCKER_TAG_ENVIRONMENT_ENABLED == true }}
      working-directory: ${{ inputs.DOCKER_WORKING_DIR }}
      run: |
        docker pull ${{ inputs.DOCKER_TAG_URL }}:${{ inputs.DOCKER_IMAGE_TAG }}
        docker tag ${{ inputs.DOCKER_TAG_URL }}:${{ inputs.DOCKER_IMAGE_TAG }} ${{ inputs.DOCKER_TAG_URL }}:${{ inputs.ENVIRONMENT }}
        docker push ${{ inputs.DOCKER_TAG_URL }}:${{ inputs.ENVIRONMENT }}
    - name: Re-tag Artifact with ShortSHA
      if: ${{ inputs.DOCKER_TAG_SHORT_SHA_ENABLED == true }}
      working-directory: ${{ inputs.DOCKER_WORKING_DIR }}
      run: |
        docker pull ${{ inputs.DOCKER_TAG_URL }}:${{ inputs.DOCKER_IMAGE_TAG }}
        docker tag ${{ inputs.DOCKER_TAG_URL }}:${{ inputs.DOCKER_IMAGE_TAG }} ${{ inputs.DOCKER_TAG_URL }}:${{ steps.git-short-sha.outputs.short_sha }}
        docker push ${{ inputs.DOCKER_TAG_URL }}:${{ steps.git-short-sha.outputs.short_sha }}
    - name: Re-tag Artifact with Ref
      if: ${{ inputs.DOCKER_TAG_REF_ENABLED == true }}
      working-directory: ${{ inputs.DOCKER_WORKING_DIR }}
      run: |
        docker pull ${{ inputs.DOCKER_TAG_URL }}:${{ inputs.DOCKER_IMAGE_TAG }}
        docker tag ${{ inputs.DOCKER_TAG_URL }}:${{ inputs.DOCKER_IMAGE_TAG }} ${{ inputs.DOCKER_TAG_URL }}:${{ steps.git-ref.outputs.tag }}
        docker push ${{ inputs.DOCKER_TAG_URL }}:${{ steps.git-ref.outputs.tag }}
    - name: Re-tag Artifact with Latest
      if: ${{ inputs.DOCKER_TAG_LATEST_ENABLED == true }}
      working-directory: ${{ inputs.DOCKER_WORKING_DIR }}
      run: |
        docker pull ${{ inputs.DOCKER_TAG_URL }}:${{ inputs.DOCKER_IMAGE_TAG }}
        docker tag ${{ inputs.DOCKER_TAG_URL }}:${{ inputs.DOCKER_IMAGE_TAG }} ${{ inputs.DOCKER_TAG_URL }}:latest
        docker push ${{ inputs.DOCKER_TAG_URL }}:latest
      
