name: Deploy Docker
on:
  workflow_call:
    inputs:
      ENVIRONMENT:
        type: string
        required: false
        default: development
      DOCKER_TAG_ENVIRONMENT_ENABLED:
        type: boolean
        required: false
        default: false
      DOCKER_TAG_LATEST_ENABLED:
        type: boolean
        required: false
        default: false
      DOCKER_TAG_SHORT_SHA_ENABLED:
        type: boolean
        required: false
        default: false
      DOCKER_TAG_REF_ENABLED:
        type: boolean
        required: false
        default: false
      DOCKER_TAG_URL:
        type: string
        required: false
        default: docker.pkg.github.com/${{ github.repository }}
      DOCKER_REGISTRY:
        type: string
        required: false
        default: docker.io
      DOCKER_REPOSITORY:
        type: string
        required: true
      DOCKER_IMAGE_TAG:
        type: string
        required: false
        default: ${{ github.sha }}
      DOCKER_DEPLOY_TAG:
        type: string
        required: false
    secrets:
      #---------------------------------------------------------------------------------------------
      # Registry
      #---------------------------------------------------------------------------------------------
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true
jobs:
  #-------------------------------------------------------------------------------------------------
  # Dockerized
  #-------------------------------------------------------------------------------------------------
  dockerized:
    name: Dockerized
    environment: ${{ inputs.ENVIRONMENT }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
        - ubuntu-24.04
    steps:
    #-----------------------------------------------------------------------------------------------
    # Checkout Repository
    #-----------------------------------------------------------------------------------------------
    - name: Prepare
      uses: actions/checkout@v3
    #-----------------------------------------------------------------------------------------------
    # Registry Repository
    #-----------------------------------------------------------------------------------------------
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.DOCKER_REGISTRY }}/${{ inputs.DOCKER_REPOSITORY }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    #-----------------------------------------------------------------------------------------------
    # Get Short SHA
    #-----------------------------------------------------------------------------------------------
    - name: Get Short SHA
      id: git-short-sha
      shell: bash
      run: |
        short=$(git rev-parse --short ${{ github.sha }})
        echo "short_sha=$short" >> $GITHUB_OUTPUT
    #-----------------------------------------------------------------------------------------------
    # Get Branch / Tag Name
    #-----------------------------------------------------------------------------------------------
    - name: Get Branch or Tag Name
      id: git-ref
      shell: bash
      run: |
        tag=$GITHUB_REF_NAME
        echo "tag=$tag" >> $GITHUB_OUTPUT
    #-----------------------------------------------------------------------------------------------
    # Re-tag
    #-----------------------------------------------------------------------------------------------
    - name: Re-tag Artifact
      if: ${{ inputs.DOCKER_DEPLOY_TAG != '' }}
      run: |
        docker pull ${{ inputs.DOCKER_TAG_URL }}:${{ inputs.DOCKER_IMAGE_TAG }}
        docker tag ${{ inputs.DOCKER_TAG_URL }}:${{ inputs.DOCKER_IMAGE_TAG }} ${{ inputs.DOCKER_TAG_URL }}:${{ inputs.DOCKER_DEPLOY_TAG }}
        docker push ${{ inputs.DOCKER_TAG_URL }}:${{ inputs.DOCKER_DEPLOY_TAG }}
    - name: Re-tag Artifact with Environment
      if: ${{ inputs.DOCKER_TAG_ENVIRONMENT_ENABLED == true }}
      run: |
        docker pull ${{ inputs.DOCKER_TAG_URL }}:${{ inputs.DOCKER_IMAGE_TAG }}
        docker tag ${{ inputs.DOCKER_TAG_URL }}:${{ inputs.DOCKER_IMAGE_TAG }} ${{ inputs.DOCKER_TAG_URL }}:${{ inputs.ENVIRONMENT }}
        docker push ${{ inputs.DOCKER_TAG_URL }}:${{ inputs.ENVIRONMENT }}
    - name: Re-tag Artifact with ShortSHA
      if: ${{ inputs.DOCKER_TAG_SHORT_SHA_ENABLED == true }}
      run: |
        docker pull ${{ inputs.DOCKER_TAG_URL }}:${{ inputs.DOCKER_IMAGE_TAG }}
        docker tag ${{ inputs.DOCKER_TAG_URL }}:${{ inputs.DOCKER_IMAGE_TAG }} ${{ inputs.DOCKER_TAG_URL }}:${{ steps.git-short-sha.outputs.short_sha }}
        docker push ${{ inputs.DOCKER_TAG_URL }}:${{ steps.git-short-sha.outputs.short_sha }}
    - name: Re-tag Artifact with Ref
      if: ${{ inputs.DOCKER_TAG_REF_ENABLED == true }}
      run: |
        docker pull ${{ inputs.DOCKER_TAG_URL }}:${{ inputs.DOCKER_IMAGE_TAG }}
        docker tag ${{ inputs.DOCKER_TAG_URL }}:${{ inputs.DOCKER_IMAGE_TAG }} ${{ inputs.DOCKER_TAG_URL }}:${{ steps.git-ref.outputs.tag }}
        docker push ${{ inputs.DOCKER_TAG_URL }}:${{ steps.git-ref.outputs.tag }}
    - name: Re-tag Artifact with Latest
      if: ${{ inputs.DOCKER_TAG_LATEST_ENABLED == true }}
      run: |
        docker pull ${{ inputs.DOCKER_TAG_URL }}:${{ inputs.DOCKER_IMAGE_TAG }}
        docker tag ${{ inputs.DOCKER_TAG_URL }}:${{ inputs.DOCKER_IMAGE_TAG }} ${{ inputs.DOCKER_TAG_URL }}:latest
        docker push ${{ inputs.DOCKER_TAG_URL }}:latest
      
