name: Deploy to Cloudflare
on:
  workflow_call:
    inputs:
      #-----------------------------------------------------------------------------------------------------------------
      # Usage
      #-----------------------------------------------------------------------------------------------------------------
      ENVIRONMENT:
        type: string
        required: false
        default: development
      #-----------------------------------------------------------------------------------------------------------------
      # Common
      #-----------------------------------------------------------------------------------------------------------------
      WORKING_DIR:
        type: string
        required: false
        default: .
      #-----------------------------------------------------------------------------------------------------------------
      # Features
      #-----------------------------------------------------------------------------------------------------------------
      # No Features
      #-----------------------------------------------------------------------------------------------------------------
      # Platform
      #-----------------------------------------------------------------------------------------------------------------
      OS_VERSION:
        type: string
        required: false
        default: ubuntu-24.04
      #-----------------------------------------------------------------------------------------------------------------
      # Artifact
      #-----------------------------------------------------------------------------------------------------------------
      ARTIFACT_NAME:
        type: string
        required: false
        default: lib
      ARTIFACT_PATH:
        type: string
        required: false
        default: lib
    secrets:
      #-----------------------------------------------------------------------------------------------------------------
      # Platform
      #-----------------------------------------------------------------------------------------------------------------
      CLOUDFLARE_API_TOKEN:
        required: true
permissions:
  id-token: write
  contents: read
jobs:
  #---------------------------------------------------------------------------------------------------------------------
  # Deploy
  #---------------------------------------------------------------------------------------------------------------------
  deploy:
    name: Deploy
    runs-on: ${{ matrix.os }}
    environment: 
      name: ${{ inputs.ENVIRONMENT }}
    strategy:
      matrix:
        os:
        - ${{ inputs.OS_VERSION }}
    steps:
    #-------------------------------------------------------------------------------------------------------------------
    # Download Artifact
    #-------------------------------------------------------------------------------------------------------------------
    - name: Download Artifact
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.ARTIFACT_NAME }}
        path: ${{ inputs.ARTIFACT_PATH }}
    #-------------------------------------------------------------------------------------------------------------------
    # Publish Package
    #-------------------------------------------------------------------------------------------------------------------
    - name: Deploy to Cloudflare Worker
      id: webapp
      uses: cloudflare/wrangler-action@v3
      with:
        apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}