name: Deploy Azure
on:
  workflow_call:
    inputs:
      #---------------------------------------------------------------------------------------------------------------------
      # Deployment
      #---------------------------------------------------------------------------------------------------------------------
      ENVIRONMENT:
        type: string
        required: false
        default: development
      #---------------------------------------------------------------------------------------------------------------------
      # Artifact
      #---------------------------------------------------------------------------------------------------------------------
      ARTIFACT_NAME:
        type: string
        required: false
        default: target
      ARTIFACT_PATH:
        type: string
        required: false
        default: target
      #---------------------------------------------------------------------------------------------------------------------
      # Azure
      #---------------------------------------------------------------------------------------------------------------------
      AZURE_TYPE:
        type: string
        required: true
      AZURE_APP_NAME:
        type: string
        required: true
      AZURE_APP_SLOT:
        type: string
        required: false
        default: production
      AZURE_ARTIFACT:
        type: string
        required: true
      AZURE_IDENTITY:
        type: string
        required: false
        default: IDENTITY
    secrets:
      #---------------------------------------------------------------------------------------------------------------------
      # Registry
      #---------------------------------------------------------------------------------------------------------------------
      AZURE_TENANT_ID:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true
      AZURE_CLIENT_ID:
        required: true
jobs:
  #---------------------------------------------------------------------------------------------------------------------
  # Deploy
  #---------------------------------------------------------------------------------------------------------------------
  deploy:
    name: Build
    runs-on: ${{ matrix.os }}
    environment: ${{ inputs.ENVIRONMENT }}
    strategy:
      matrix:
        java-version:
        - ${{ inputs.JAVA_VERSION }}
        os:
        - ubuntu-latest
    steps:
    # Download Artifact
    - name: Download Artifact
      uses: actions/download-artifact@v4.1.7
      with:
        name: ${{ inputs.ARTIFACT_NAME }}
        path: ${{ inputs.ARTIFACT_PATH }}
    # Azure Login
    - name: Login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    # Deploy to WebApp
    - name: Deploy to Azure Web App
      if: ${{ inputs.AZURE_TYPE == 'WebApp' }}
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ inputs.AZURE_APP_NAME }}
        slot-name: ${{ inputs.AZURE_APP_SLOT }}
        package: ${{ inputs.AZURE_ARTIFACT }}
