name: Remove artifacts
on:
  workflow_call:
    inputs:
      #-----------------------------------------------------------------------------------------------------------------
      # Usage
      #-----------------------------------------------------------------------------------------------------------------
      # No Usage
      #-----------------------------------------------------------------------------------------------------------------
      # Common
      #-----------------------------------------------------------------------------------------------------------------
      # No Common
      #-----------------------------------------------------------------------------------------------------------------
      # Features
      #-----------------------------------------------------------------------------------------------------------------
      # No Features
      #-----------------------------------------------------------------------------------------------------------------
      # Platform
      #-----------------------------------------------------------------------------------------------------------------
      OS_VERSION:
        type: string
        required: false
        default: ubuntu-24.04
      #-----------------------------------------------------------------------------------------------------------------
      # Registry
      #-----------------------------------------------------------------------------------------------------------------
      # No Registry
      #-----------------------------------------------------------------------------------------------------------------
      # Artifact
      #-----------------------------------------------------------------------------------------------------------------
      # No Artifact
      #-----------------------------------------------------------------------------------------------------------------
jobs:
  #---------------------------------------------------------------------------------------------------------------------
  # Clean Up
  #---------------------------------------------------------------------------------------------------------------------
  cleanup:
    name: Clean Up
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
        - ${{ inputs.OS_VERSION }}
    permissions:
      actions: write
    timeout-minutes: 10
    steps:
    #-------------------------------------------------------------------------------------------------------------------
    # Remove Artifact
    #-------------------------------------------------------------------------------------------------------------------
    - name: Remove old artifacts
      uses: c-hive/gha-remove-artifacts@v1
      with:
        age: "1 day"
