name: Remove artifacts
on:
  schedule:
  - cron: '0 1 * * *'
jobs:
  cleanup:
    name: Clean Up
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
        - ubuntu-24.04
    timeout-minutes: 10
    steps:
    - name: Remove old artifacts
      uses: c-hive/gha-remove-artifacts@v1
      with:
        age: '1 day'