name: Release GitHub
on:
  workflow_call:
    inputs:
      #---------------------------------------------------------------------------------------------------------------------
      # Platform
      #---------------------------------------------------------------------------------------------------------------------
      MAJOR_VERSION:
        type: number
        required: false
        default: 0
      MINOR_VERSION:
        type: number
        required: false
        default: 0
      INCREMENTAL_VERSION:
        type: number
        required: false
        default: 1
      #---------------------------------------------------------------------------------------------------------------------
      # Deployment
      #---------------------------------------------------------------------------------------------------------------------
      ENVIRONMENT:
        type: string
        required: false
        default: development
      #---------------------------------------------------------------------------------------------------------------------
      # Artifact
      #---------------------------------------------------------------------------------------------------------------------
      ARTIFACT_ASSETS:
        type: string
        required: true
      ARTIFACT_NAME:
        type: string
        required: false
        default: lib
      ARTIFACT_PATH:
        type: string
        required: false
        default: assets/lib
      #---------------------------------------------------------------------------------------------------------------------
      # Coverage
      #---------------------------------------------------------------------------------------------------------------------
      COVERAGE_ENABLED:
        type: boolean
        required: false
        default: false
      COVERAGE_NAME:
        type: string
        required: false
        default: coverage
      COVERAGE_PATH:
        type: string
        required: false
        default: assets/coverage
      #---------------------------------------------------------------------------------------------------------------------
      # Docs
      #---------------------------------------------------------------------------------------------------------------------
      DOCS_ENABLED:
        type: boolean
        required: false
        default: false
      DOCS_NAME:
        type: string
        required: false
        default: docs
      DOCS_PATH:
        type: string
        required: false
        default: assets/docs
env:
  tag_name: ${{ inputs.MAJOR_VERSION }}.${{ inputs.MINOR_VERSION }}.${{ inputs.INCREMENTAL_VERSION }}
jobs:
  #---------------------------------------------------------------------------------------------------------------------
  # Release
  #---------------------------------------------------------------------------------------------------------------------
  release:
    name: Release
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ ubuntu-latest ]
    steps:
    # Prepare Repository
    - name: Prepare
      uses: actions/checkout@v4
      with:
        ref: ${{ env.tag_name }}
    # Download Artifact Binary
    - name: Download Assets
      uses: actions/download-artifact@v3
      with:
        name: ${{ inputs.ARTIFACT_NAME }}
        path: ${{ inputs.ARTIFACT_PATH }}
    # Download Artifact Coverage
    - name: Download Coverage
      if: ${{ inputs.COVERAGE_ENABLED == true }}
      uses: actions/download-artifact@v3
      with:
        name: ${{ inputs.COVERAGE_NAME }}
        path: ${{ inputs.COVERAGE_PATH }}
    # Download Artifact Docs
    - name: Download Documentation
      if: ${{ inputs.DOCS_ENABLED == true }}
      uses: actions/download-artifact@v3
      with:
        name: ${{ inputs.DOCS_NAME }}
        path: ${{ inputs.DOCS_PATH }}
    # Setup Artifact Coverage
    - name: Setup Coverage Asset
      if: ${{ inputs.COVERAGE_ENABLED == true }}
      run: mv ${{ inputs.COVERAGE_PATH }} assets/coverage
    # Setup Artifact Docs
    - name: Setup Docs Asset
      if: ${{ inputs.DOCS_ENABLED == true }}
      run: mv ${{ inputs.DOCS_PATH }} assets/docs
    # Packaging
    - name: Packaging Assets
      run: zip -r ${{ env.tag_name }}.zip ${{ inputs.ARTIFACT_ASSETS }}
    # Release
    - name: Create Release
      id: create-release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ env.tag_name }}
        release_name: Release ${{ env.tag_name }}
        body_path: docs/release-notes/${{ env.tag_name }}.md
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    # Upload Release
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create-release.outputs.upload_url }}
        asset_path: ./${{ env.tag_name }}.zip
        asset_name: ${{ github.event.repository.name }}}-${{ env.tag_name }}.zip
        asset_content_type: application/zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}