name: Deploy Helm Chart
on:
  workflow_call:
    inputs:
      #-----------------------------------------------------------------------------------------------------------------
      # Usage
      #-----------------------------------------------------------------------------------------------------------------
      HELM_REPOSITORY:
        type: string
        required: false
        default: ${{ github.repository }}
      HELM_CHART_NAME:
        type: string
        required: false
        default: ${{ github.event.repository.name }}
      #-----------------------------------------------------------------------------------------------------------------
      # Common
      #-----------------------------------------------------------------------------------------------------------------
      WORKING_DIR:
        type: string
        required: false
        default: .
      #-----------------------------------------------------------------------------------------------------------------
      # Features
      #-----------------------------------------------------------------------------------------------------------------
      # No Features
      #-----------------------------------------------------------------------------------------------------------------
      # Platform
      #-----------------------------------------------------------------------------------------------------------------
      OS_VERSION:
        type: string
        required: false
        default: ubuntu-24.04
      #-----------------------------------------------------------------------------------------------------------------
      # Registry
      #-----------------------------------------------------------------------------------------------------------------
      # No Registry
      #-----------------------------------------------------------------------------------------------------------------
      # Artifact
      #-----------------------------------------------------------------------------------------------------------------
      ARTIFACT_NAME:
        type: string
        required: false
        default: ${{ github.event.repository.name }}-0.1.0.tgz
      ARTIFACT_PATH:
        type: string
        required: false
        default: ${{ github.event.repository.name }}-0.1.0.tgz
      ARTIFACT_RETENTION:
        type: string
        required: false
        default: "1"
    secrets:
      #-----------------------------------------------------------------------------------------------------------------
      # Registry
      #-----------------------------------------------------------------------------------------------------------------
      HELM_AUTH_TOKEN:
        required: true
jobs:
  #---------------------------------------------------------------------------------------------------------------------
  # Deploy
  #---------------------------------------------------------------------------------------------------------------------
  deploy:
    runs-on: ubuntu-latest
    steps:
    #-------------------------------------------------------------------------------------------------------------------
    # Prepare Repository
    #-------------------------------------------------------------------------------------------------------------------
    - name: Checkout code
      uses: actions/checkout@v4
    #-------------------------------------------------------------------------------------------------------------------
    # Download Artifact
    #-------------------------------------------------------------------------------------------------------------------
    - name: Download Artifact
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.ARTIFACT_NAME }}
        path: ${{ inputs.ARTIFACT_PATH }}
    #-------------------------------------------------------------------------------------------------------------------
    # Setup Platform
    #-------------------------------------------------------------------------------------------------------------------
    - name: Set up Helm
      uses: azure/setup-helm@v4
    #-------------------------------------------------------------------------------------------------------------------
    # Helm Versions
    #-------------------------------------------------------------------------------------------------------------------
    - name: Get Helm Version
      id: versions
      uses: bayudwiyansatria/.github/actions/helm-get-version@master
      with:
        checkout: false
        working-directory: ${{ inputs.WORKING_DIR }}/${{ inputs.HELM_CHART_NAME }}
    #-------------------------------------------------------------------------------------------------------------------
    # Publish Package
    #-------------------------------------------------------------------------------------------------------------------
    - name: Push Helm Chart
      run: helm push ${{ inputs.ARTIFACT_NAME }}
      env:
        HELM_REPO_URL: ${{ secrets.HELM_REPOSITORY }}
        HELM_REPO_TOKEN: ${{ secrets.HELM_AUTH_TOKEN }}