name: Release Maven
on:
  workflow_call:
    inputs:
      #------------------------------------------------------------------------------------------------------------------
      # Version
      #------------------------------------------------------------------------------------------------------------------
      MAJOR_VERSION:
        type: string
        required: false
        default: "0"
      MINOR_VERSION:
        type: string
        required: false
        default: "0"
      INCREMENTAL_VERSION:
        type: string
        required: false
        default: "1"
      #-----------------------------------------------------------------------------------------------------------------
      # Usage
      #-----------------------------------------------------------------------------------------------------------------
      #-----------------------------------------------------------------------------------------------------------------
      # Platform
      #-----------------------------------------------------------------------------------------------------------------
      OS_VERSION:
        type: string
        required: false
        default: ubuntu-24.04
      JAVA_VERSION:
        type: number
        required: false
        default: 11
      #-----------------------------------------------------------------------------------------------------------------
      # Artifact
      #-----------------------------------------------------------------------------------------------------------------
      ARTIFACT_NAME:
        type: string
        required: false
        default: target
      ARTIFACT_PATH:
        type: string
        required: false
        default: target
    secrets:
      #-----------------------------------------------------------------------------------------------------------------
      # Registry
      #-----------------------------------------------------------------------------------------------------------------
      MAVEN_USERNAME:
        required: true
      MAVEN_PASSWORD:
        required: true
permissions:
  contents: write
  id-token: write
env:
  tag_name: ${{ inputs.MAJOR_VERSION }}.${{ inputs.MINOR_VERSION }}.${{ inputs.INCREMENTAL_VERSION }}
jobs:
  #---------------------------------------------------------------------------------------------------------------------
  # Deploy
  #---------------------------------------------------------------------------------------------------------------------
  deploy:
    name: Snapshot
    uses: bayudwiyansatria/.github/.github/workflows/deploy-maven.yml@master
    with:
      JAVA_VERSION: 11
    secrets:
      MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
      MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
  #---------------------------------------------------------------------------------------------------------------------
  # Release
  #---------------------------------------------------------------------------------------------------------------------
  release:
    name: Release
    needs:
    - deploy
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        java-version:
        - ${{ inputs.JAVA_VERSION }}
        os:
        - ${{ inputs.OS_VERSION }}
    steps:
    #-------------------------------------------------------------------------------------------------------------------
    # Prepare Repository
    #-------------------------------------------------------------------------------------------------------------------
    - name: Prepare
      uses: actions/checkout@v3
    #-------------------------------------------------------------------------------------------------------------------
    # Download Artifact
    #-------------------------------------------------------------------------------------------------------------------
    - name: Download Artifact
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.ARTIFACT_NAME }}
        path: ${{ inputs.ARTIFACT_PATH }}
    #-------------------------------------------------------------------------------------------------------------------
    # Setup Platform
    #-------------------------------------------------------------------------------------------------------------------
    - name: Configure Java
      uses: bayudwiyansatria/.github/actions/configure-java@master
      with:
        java-version: ${{ inputs.JAVA_VERSION }}
        gpg-sign: true
    #-------------------------------------------------------------------------------------------------------------------
    # Publish Package
    #-------------------------------------------------------------------------------------------------------------------
    - name: Prepare Deployment
      run: >-
        mvn
        --no-transfer-progress
        --settings settings.xml
        build-helper:parse-version
        versions:set -DnewVersion=\${{ env.tag_name }}
        versions:commit
      env:
        MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
    #-------------------------------------------------------------------------------------------------------------------
    # Setup Git
    #-------------------------------------------------------------------------------------------------------------------
    - name: Configure Git
      uses: bayudwiyansatria/.github/actions/git-configure@master
    - name: Prepare Deployment
      run: |
        git checkout -b tmp
        export CURRENT_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
        git add .
        git commit -m "[SKIP CI] Release ${CURRENT_VERSION}"
        git push origin tmp:master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_PAT }}
    - name: Tag Git
      uses: bayudwiyansatria/.github/actions/git-tag@master
      with:
        tag: ${{ env.tag_name }}
        git-token: ${{ secrets.GITHUB_PAT }}
    #-------------------------------------------------------------------------------------------------------------------
    # Publish Package
    #-------------------------------------------------------------------------------------------------------------------
    - name: Deployment
      run: >-
        mvn
        --batch-mode
        --no-transfer-progress
        --settings settings.xml
        --file pom.xml
        package
        gpg:sign
        deploy
        -DskipTests
      env:
        MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
        GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
    - name: Post Deployment
      run: >-
        mvn
        --no-transfer-progress
        --settings settings.xml
        build-helper:parse-version
        versions:set -DnewVersion=\${{ env.tag_name }}-SNAPSHOT
        versions:commit
      env:
        MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
    - name: Reconfigure Java
      run: |
        export CURRENT_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
        git add .
        git commit -m "[SKIP CI] Set ${CURRENT_VERSION}"
        git push origin tmp:master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_PAT }}