name: Main
on:
  workflow_call:
    inputs:
      #---------------------------------------------------------------------------------------------------------------------
      # Platform
      #---------------------------------------------------------------------------------------------------------------------
      MAJOR_VERSION:
        type: string
        required: false
        default: 0
      MINOR_VERSION:
        type: string
        required: false
        default: 0
      INCREMENTAL_VERSION:
        type: string
        required: false
        default: 1
      #---------------------------------------------------------------------------------------------------------------------
      # Deployment
      #---------------------------------------------------------------------------------------------------------------------
      ENVIRONMENT:
        type: string
        required: false
        default: development
      #---------------------------------------------------------------------------------------------------------------------
      # Artifact
      #---------------------------------------------------------------------------------------------------------------------
      ARTIFACT_NAME:
        type: string
        required: false
        default: target
      ARTIFACT_PATH:
        type: string
        required: false
        default: target
    secrets:
      #---------------------------------------------------------------------------------------------------------------------
      # Registry
      #---------------------------------------------------------------------------------------------------------------------
      GITHUB_TOKEN:
        required: true
env:
  tag_name: ${{ inputs.MAJOR_VERSION }}.${{ inputs.MINOR_VERSION }}.${{ inputs.INCREMENTAL_VERSION }}
jobs:
  #---------------------------------------------------------------------------------------------------------------------
  # Release
  #---------------------------------------------------------------------------------------------------------------------
  release:
    name: Release
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        java-version: [ 11.0.3 ]
        operating-system: [ ubuntu-latest ]
    steps:
    # Prepare Repository
    - name: Prepare
      uses: actions/checkout@v3
    # Download Artifact
    - name: Download Artifact
      uses: actions/download-artifact@v3
      with:
        name: ${{ inputs.ARTIFACT_NAME }}
        path: ${{ inputs.ARTIFACT_PATH }}
    # Packaging
    - name: Packaging Assets
      run: zip -r ${{ env.tag_name }}.zip dist README.md package.json
    # Release
    - name: Create Release
      id: create-release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ env.tag_name }}
        release_name: Release ${{ env.tag_name }}
        body_path: docs/release-notes/${{ env.tag_name }}.md
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    # Upload Release
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create-release.outputs.upload_url }}
        asset_path: ./${{ env.tag_name }}.zip
        asset_name: ${{ github.event.repository.name }}-${{ env.tag_name }}.zip
        asset_content_type: application/zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}