name: Release Maven
on:
  workflow_call:
    inputs:
      #---------------------------------------------------------------------------------------------------------------------
      # Platform
      #---------------------------------------------------------------------------------------------------------------------
      JAVA_VERSION:
        type: string
        required: false
        default: 11
      MAJOR_VERSION:
        type: string
        required: false
        default: 0
      MINOR_VERSION:
        type: string
        required: false
        default: 0
      INCREMENTAL_VERSION:
        type: string
        required: false
        default: 1
      #---------------------------------------------------------------------------------------------------------------------
      # Artifact
      #---------------------------------------------------------------------------------------------------------------------
      ARTIFACT_NAME:
        type: string
        required: false
        default: target
      ARTIFACT_PATH:
        type: string
        required: false
        default: target
    secrets:
      #---------------------------------------------------------------------------------------------------------------------
      # Registry
      #---------------------------------------------------------------------------------------------------------------------
      MAVEN_USERNAME:
        required: true
      MAVEN_PASSWORD:
        required: true
permissions:
  contents: write
  id-token: write
env:
  tag_name: ${{ inputs.MAJOR_VERSION }}.${{ inputs.MINOR_VERSION }}.${{ inputs.INCREMENTAL_VERSION }}
jobs:
  #---------------------------------------------------------------------------------------------------------------------
  # Deploy
  #---------------------------------------------------------------------------------------------------------------------
  deploy:
    name: Snapshot
    uses: bayudwiyansatria/.github/.github/workflows/deploy-maven.yaml@master
    with:
      JAVA_VERSION: 11
    secrets:
      MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
      MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
  #---------------------------------------------------------------------------------------------------------------------
  # Release
  #---------------------------------------------------------------------------------------------------------------------
  release:
    name: Release
    needs:
    - deploy
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        java-version:
        - ${{ inputs.JAVA_VERSION }}
        operating-system:
        - ubuntu-latest
    steps:
    # Prepare Repository
    - name: Prepare
      uses: actions/checkout@v3
    # Download Artifact
    - name: Download Artifact
      uses: actions/download-artifact@v3
      with:
        name: ${{ inputs.ARTIFACT_NAME }}
        path: ${{ inputs.ARTIFACT_PATH }}
    # Setup Java
    - name: Set Up Java Development Kit
      uses: actions/setup-java@v2
      with:
        java-version: ${{ matrix.java-version }}
        distribution: adopt
        cache: maven
        gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
        gpg-passphrase: GPG_PASSPHRASE
    # Prepare Deployment
    - name: Prepare Deployment
      run: >-
        mvn
        --no-transfer-progress
        --settings settings.xml
        build-helper:parse-version
        versions:set -DnewVersion=\${{ env.tag_name }}
        versions:commit
      env:
        MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
    # Configure Git
    - name: Configure Git user
      run: |
        git config user.email "actions@github.com"
        git config user.name "GitHub Actions"
        git checkout -b tmp
        export CURRENT_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
        git add .
        git commit -m "[SKIP CI] Release ${CURRENT_VERSION}"
        git push origin tmp:master
        git tag ${{ env.tag_name }}
        git push origin ${{ env.tag_name }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_PAT }}
    # Deployment
    - name: Deployment
      run: >-
        mvn
        --batch-mode
        --no-transfer-progress
        --settings settings.xml
        --file pom.xml
        package
        gpg:sign
        deploy
        -DskipTests
      env:
        MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
        GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
    # Post Deployment
    - name: Post Deployment
      run: >-
        mvn
        --no-transfer-progress
        --settings settings.xml
        build-helper:parse-version
        versions:set -DnewVersion=\${{ env.tag_name }}-SNAPSHOT
        versions:commit
      env:
        MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
    - name: Reconfigure Git user
      run: |
        export CURRENT_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
        git add .
        git commit -m "[SKIP CI] Set ${CURRENT_VERSION}"
        git push origin tmp:master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_PAT }}