name: Release GitHub Pages
on:
  workflow_call:
    inputs:
      #-----------------------------------------------------------------------------------------------------------------
      # Usage
      #-----------------------------------------------------------------------------------------------------------------
      # No Usage
      #-----------------------------------------------------------------------------------------------------------------
      # Common
      #-----------------------------------------------------------------------------------------------------------------
      # No Common
      #-----------------------------------------------------------------------------------------------------------------
      # Features
      #-----------------------------------------------------------------------------------------------------------------
      # No Features
      #-----------------------------------------------------------------------------------------------------------------
      # Platform
      #-----------------------------------------------------------------------------------------------------------------
      OS_VERSION:
        type: string
        required: false
        default: ubuntu-24.04
      #-----------------------------------------------------------------------------------------------------------------
      # Registry
      #-----------------------------------------------------------------------------------------------------------------
      # No Registry
      #-----------------------------------------------------------------------------------------------------------------
      # Artifact
      #-----------------------------------------------------------------------------------------------------------------
      ARTIFACT_NAME:
        type: string
        required: false
        default: dist
      ARTIFACT_PATH:
        type: string
        required: false
        default: dist
      ARTIFACT_ROOT:
        type: string
        required: false
        default: dist
    secrets:
      #-----------------------------------------------------------------------------------------------------------------
      # GitHub
      #-----------------------------------------------------------------------------------------------------------------
      GITHUB_PAT:
        required: true
jobs:
  #---------------------------------------------------------------------------------------------------------------------
  # Release
  #---------------------------------------------------------------------------------------------------------------------
  pages:
    name: Deploy GitHub Pages
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
        - ${{ inputs.OS_VERSION }}
    steps:
    #-------------------------------------------------------------------------------------------------------------------
    # Prepare Repository
    #-------------------------------------------------------------------------------------------------------------------
    - name: Checkout
      uses: actions/checkout@v7
    #-------------------------------------------------------------------------------------------------------------------
    # Download Artifact
    #-------------------------------------------------------------------------------------------------------------------
    - name: Download Artifact
      uses: actions/download-artifact@v7
      with:
        name: ${{ inputs.ARTIFACT_NAME }}
        path: ${{ inputs.ARTIFACT_PATH }}
    #-------------------------------------------------------------------------------------------------------------------
    # Setup Platform
    #-------------------------------------------------------------------------------------------------------------------
    - name: Setup Pages
      uses: actions/configure-pages@v6
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_PAT }}
    - name: Upload Pages Artifact
      uses: actions/upload-pages-artifact@v5
      with:
        path: ${{ inputs.ARTIFACT_ROOT }}
        include-hidden-files: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_PAT }}
    - name: Deploy GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_PAT }}
