name: Release GitHub Pages
on:
  workflow_call:
    inputs:
      #---------------------------------------------------------------------------------------------------------------------
      # Artifact
      #---------------------------------------------------------------------------------------------------------------------
      ARTIFACT_NAME:
        type: string
        required: false
        default: dist
      ARTIFACT_PATH:
        type: string
        required: false
        default: dist
      ARTIFACT_ROOT:
        type: string
        required: false
        default: dist
    secrets:
      #---------------------------------------------------------------------------------------------------------------------
      # GitHub
      #---------------------------------------------------------------------------------------------------------------------
      GITHUB_PAT:
        required: true
jobs:
  release:
    if: ${{ github.event_name == 'workflow_call' }}
    name: Deploy GitHub Pages
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: 
        - ubuntu-24.04
    steps:
    #-------------------------------------------------------------------------------------------------------------------------
    # Prepare Repository
    #-------------------------------------------------------------------------------------------------------------------------
    - name: Checkout
      uses: actions/checkout@v3
    #-------------------------------------------------------------------------------------------------------------------------
    # Download Artifact
    #-------------------------------------------------------------------------------------------------------------------------
    - name: Download Artifact
      uses: actions/download-artifact@v3
      with:
        name: ${{ inputs.ARTIFACT_NAME }}
        path: ${{ inputs.ARTIFACT_PATH }}
    #-------------------------------------------------------------------------------------------------------------------------
    # Setup Platform
    #-------------------------------------------------------------------------------------------------------------------------
    - name: Setup Pages
      uses: actions/configure-pages@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_PAT }}
    - name: Upload Pages Artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: ${{ inputs.ARTIFACT_ROOT }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_PAT }}
    - name: Deploy GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_PAT }}
