name: Test Node NPM
on:
  workflow_call:
    inputs:
      #-----------------------------------------------------------------------------------------------------------------
      # Platform
      #-----------------------------------------------------------------------------------------------------------------
      NODE_VERSION:
        type: string
        required: false
        default: "16"
      #-----------------------------------------------------------------------------------------------------------------
      # Registry
      #-----------------------------------------------------------------------------------------------------------------
      NPM_REGISTRY:
        type: string
        required: false
        default: https://npm.pkg.github.com
      #-----------------------------------------------------------------------------------------------------------------
      # Artifact
      #-----------------------------------------------------------------------------------------------------------------
      BUILD_ARTIFACT_NAME:
        type: string
        required: false
        default: lib
      BUILD_ARTIFACT_PATH:
        type: string
        required: false
        default: lib
      ARTIFACT_REPOSITORY:
        type: string
        required: true
      ARTIFACT_NAME:
        type: string
        required: false
        default: coverage
      ARTIFACT_PATH:
        type: string
        required: false
        default: dist/coverage
      ARTIFACT_RETENTION:
        type: string
        required: false
        default: "1"
    secrets:
      #-----------------------------------------------------------------------------------------------------------------
      # Registry
      #-----------------------------------------------------------------------------------------------------------------
      NPM_AUTH_TOKEN:
        required: true
      #-----------------------------------------------------------------------------------------------------------------
      # CodeQuality
      #-----------------------------------------------------------------------------------------------------------------
      CODECOV_TOKEN:
        required: true
jobs:
  #---------------------------------------------------------------------------------------------------------------------
  # Test
  #---------------------------------------------------------------------------------------------------------------------
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version:
        - ${{ inputs.NODE_VERSION }}
        os:
        - ubuntu-24.04
    steps:
    #-------------------------------------------------------------------------------------------------------------------
    # Prepare Repository
    #-------------------------------------------------------------------------------------------------------------------
    - name: Prepare
      uses: actions/checkout@v3
    #-------------------------------------------------------------------------------------------------------------------
    # Download Artifact
    #-------------------------------------------------------------------------------------------------------------------
    - name: Download Lib
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.BUILD_ARTIFACT_NAME }}
        path: ${{ inputs.BUILD_ARTIFACT_PATH }}
    #-------------------------------------------------------------------------------------------------------------------
    # Setup Platform
    #-------------------------------------------------------------------------------------------------------------------
    - name: Configure Node
      uses: bayudwiyansatria/.github/.github/actions/configure-node@master
      with:
        node-version: ${{ inputs.NODE_VERSION }}
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
    #-------------------------------------------------------------------------------------------------------------------
    # Installing Package
    #-------------------------------------------------------------------------------------------------------------------
    - name: Installing Node Packages
      run: npm ci
    #-------------------------------------------------------------------------------------------------------------------
    # Run Unit Test
    #-------------------------------------------------------------------------------------------------------------------
    - name: Run Unit Test
      run: npm run test --if-present
    #-------------------------------------------------------------------------------------------------------------------
    # Upload Artifact
    #-------------------------------------------------------------------------------------------------------------------
    - name: Archive Coverage Result
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.ARTIFACT_NAME }}
        path: ${{ inputs.ARTIFACT_PATH }}
        retention-days: ${{ inputs.ARTIFACT_RETENTION }}
  #---------------------------------------------------------------------------------------------------------------------
  # Code Analysis
  #---------------------------------------------------------------------------------------------------------------------
  code-analysis:
    name: Code Quality
    needs: 
    - test
    uses: bayudwiyansatria/.github/.github/workflows/code-analysis-codecov.yml@master
    with:
      ARTIFACT_REPOSITORY: ${{ inputs.ARTIFACT_REPOSITORY }}
      ARTIFACT_NAME: ${{ inputs.ARTIFACT_NAME }}
      ARTIFACT_PATH: ${{ inputs.ARTIFACT_PATH }}
      ARTIFACT_RETENTION: ${{ inputs.ARTIFACT_RETENTION }}
      ARTIFACT_FILE: clover.xml
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
