name: Test Java Maven
on:
  workflow_call:
    inputs:
      #-----------------------------------------------------------------------------------------------------------------
      # Usage
      #-----------------------------------------------------------------------------------------------------------------
      MAVEN_COMMAND:
        type: string
        required: false
        default: mvn --no-transfer-progress --file pom.xml clean test package
      #-----------------------------------------------------------------------------------------------------------------
      # Common
      #-----------------------------------------------------------------------------------------------------------------
      WORKING_DIR:
        type: string
        required: false
        default: .
      #-----------------------------------------------------------------------------------------------------------------
      # Features
      #-----------------------------------------------------------------------------------------------------------------
      # No Features
      #-----------------------------------------------------------------------------------------------------------------
      # Platform
      #-----------------------------------------------------------------------------------------------------------------
      OS_VERSION:
        type: string
        required: false
        default: ubuntu-24.04
      JAVA_VERSION:
        type: string
        required: false
        default: "11"
      #-----------------------------------------------------------------------------------------------------------------
      # Registry
      #-----------------------------------------------------------------------------------------------------------------
      MAVEN_REGISTRY:
        type: string
        required: false
        default: maven.pkg.github.com
      #-----------------------------------------------------------------------------------------------------------------
      # Artifact
      #-----------------------------------------------------------------------------------------------------------------
      BUILD_ARTIFACT_NAME:
        type: string
        required: false
        default: target
      BUILD_ARTIFACT_PATH:
        type: string
        required: false
        default: target
      TEST_ARTIFACT_NAME:
        type: string
        required: false
        default: coverage
      TEST_ARTIFACT_PATH:
        type: string
        required: false
        default: target/site/jacoco
      TEST_ARTIFACT_RETENTION:
        type: string
        required: false
        default: "1"
    secrets:
      #-----------------------------------------------------------------------------------------------------------------
      # Registry
      #-----------------------------------------------------------------------------------------------------------------
      MAVEN_USERNAME:
        required: true
      MAVEN_PASSWORD:
        required: true
jobs:
  #---------------------------------------------------------------------------------------------------------------------
  # Test
  #---------------------------------------------------------------------------------------------------------------------
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        java-version:
        - ${{ inputs.JAVA_VERSION }}
        os:
        - ${{ inputs.OS_VERSION }}
    steps:
    #-------------------------------------------------------------------------------------------------------------------
    # Prepare Repository
    #-------------------------------------------------------------------------------------------------------------------
    - name: Prepare
      uses: actions/checkout@v4
    #-------------------------------------------------------------------------------------------------------------------
    # Download Artifact
    #-------------------------------------------------------------------------------------------------------------------
    - name: Download Build
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.BUILD_ARTIFACT_NAME }}
        path: ${{ inputs.BUILD_ARTIFACT_PATH }}
    #-------------------------------------------------------------------------------------------------------------------
    # Setup Platform
    #-------------------------------------------------------------------------------------------------------------------
    - name: Configure Java
      uses: bayudwiyansatria/.github/actions/configure-java@master
      with:
        java-version: ${{ inputs.JAVA_VERSION }}
    #-------------------------------------------------------------------------------------------------------------------
    # Run Unit Test
    #-------------------------------------------------------------------------------------------------------------------
    - name: Build Maven Packages
      run: ${{ inputs.MAVEN_COMMAND }}
      working-directory: ${{ inputs.WORKING_DIR }}
    #-------------------------------------------------------------------------------------------------------------------
    # Upload Artifact
    #-------------------------------------------------------------------------------------------------------------------
    - name: Archive Coverage Result
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.TEST_ARTIFACT_NAME }}
        path: ${{ inputs.TEST_ARTIFACT_PATH }}
        retention-days: ${{ inputs.TEST_ARTIFACT_RETENTION }}
