name: Test Node NPM
on:
  workflow_call:
    inputs:
      #-----------------------------------------------------------------------------------------------------------------
      # Usage
      #-----------------------------------------------------------------------------------------------------------------
      NODE_COMMAND:
        type: string
        required: false
        default: npm run test --if-present
      #-----------------------------------------------------------------------------------------------------------------
      # Common
      #-----------------------------------------------------------------------------------------------------------------
      WORKING_DIR:
        type: string
        required: false
        default: .
      #-----------------------------------------------------------------------------------------------------------------
      # Features
      #-----------------------------------------------------------------------------------------------------------------
      # No Features
      #-----------------------------------------------------------------------------------------------------------------
      # Platform
      #-----------------------------------------------------------------------------------------------------------------
      OS_VERSION:
        type: string
        required: false
        default: ubuntu-24.04
      NODE_VERSION:
        type: string
        required: false
        default: "16"
      #-----------------------------------------------------------------------------------------------------------------
      # Registry
      #-----------------------------------------------------------------------------------------------------------------
      NPM_REGISTRY:
        type: string
        required: false
        default: https://npm.pkg.github.com
      #-----------------------------------------------------------------------------------------------------------------
      # Artifact
      #-----------------------------------------------------------------------------------------------------------------
      BUILD_ARTIFACT_NAME:
        type: string
        required: false
        default: lib
      BUILD_ARTIFACT_PATH:
        type: string
        required: false
        default: lib
      TEST_ARTIFACT_NAME:
        type: string
        required: false
        default: coverage
      TEST_ARTIFACT_PATH:
        type: string
        required: false
        default: dist/coverage
      TEST_ARTIFACT_RETENTION:
        type: string
        required: false
        default: "1"
    secrets:
      #-----------------------------------------------------------------------------------------------------------------
      # Registry
      #-----------------------------------------------------------------------------------------------------------------
      NPM_AUTH_TOKEN:
        required: true
      #-----------------------------------------------------------------------------------------------------------------
      # CodeQuality
      #-----------------------------------------------------------------------------------------------------------------
      CODECOV_TOKEN:
        required: true
jobs:
  #---------------------------------------------------------------------------------------------------------------------
  # Test
  #---------------------------------------------------------------------------------------------------------------------
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version:
        - ${{ inputs.NODE_VERSION }}
        os:
        - ${{ inputs.OS_VERSION }}
    steps:
    #-------------------------------------------------------------------------------------------------------------------
    # Prepare Repository
    #-------------------------------------------------------------------------------------------------------------------
    - name: Prepare
      uses: actions/checkout@v4
    #-------------------------------------------------------------------------------------------------------------------
    # Download Artifact
    #-------------------------------------------------------------------------------------------------------------------
    - name: Download Build
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.BUILD_ARTIFACT_NAME }}
        path: ${{ inputs.BUILD_ARTIFACT_PATH }}
    #-------------------------------------------------------------------------------------------------------------------
    # Setup Platform
    #-------------------------------------------------------------------------------------------------------------------
    - name: Configure Node
      uses: bayudwiyansatria/.github/actions/configure-node@master
      with:
        node-version: ${{ inputs.NODE_VERSION }}
        registry-url: ${{ inputs.NPM_REGISTRY }}
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
    #-------------------------------------------------------------------------------------------------------------------
    # Installing Package
    #-------------------------------------------------------------------------------------------------------------------
    - name: Installing Node Packages
      run: npm ci
      working-directory: ${{ inputs.WORKING_DIR }}
    #-------------------------------------------------------------------------------------------------------------------
    # Run Unit Test
    #-------------------------------------------------------------------------------------------------------------------
    - name: Run Unit Test
      run: ${{ inputs.NODE_COMMAND }}
      working-directory: ${{ inputs.WORKING_DIR }}
    #-------------------------------------------------------------------------------------------------------------------
    # Upload Artifact
    #-------------------------------------------------------------------------------------------------------------------
    - name: Archive Coverage Result
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.TEST_ARTIFACT_NAME }}
        path: ${{ inputs.TEST_ARTIFACT_PATH }}
        retention-days: ${{ inputs.TEST_ARTIFACT_RETENTION }}
