name: Test Node
on:
  workflow_call:
    inputs:
      #---------------------------------------------------------------------------------------------------------------------
      # Platform
      #---------------------------------------------------------------------------------------------------------------------
      NODE_VERSION:
        type: string
        required: false
        default: 16
      #---------------------------------------------------------------------------------------------------------------------
      # Registry
      #---------------------------------------------------------------------------------------------------------------------
      NPM_REGISTRY:
        type: string
        required: true
    secrets:
      #---------------------------------------------------------------------------------------------------------------------
      # Registry
      #---------------------------------------------------------------------------------------------------------------------
      NPM_AUTH_TOKEN:
        required: true
jobs:
  #---------------------------------------------------------------------------------------------------------------------
  # Test
  #---------------------------------------------------------------------------------------------------------------------
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version:
        - ${{ inputs.NODE_VERSION }}
        os:
        - ubuntu-latest
    steps:
    # Prepare Repository
    - name: Prepare
      uses: actions/checkout@v3
    # Setup Node
    - name: Set Up Node
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: ${{ inputs.NPM_REGISTRY }}
        cache: npm
        always-auth: true
        check-latest: false
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
    # Installing Package
    - name: Installing Node Packages
      run: npm ci
    # Run Test
    - name: Test
      run: npm run test --if-present
    - name: Coverage Result Analysis
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        directory: ./dist/coverage
        files: clover.xml
        flags: unittests
        name: ${{ github.event.repository.name }}
        fail_ci_if_error: true
    # Only Upload If Workflow Called
    - name: Archive Coverage Result
      if: ${{ github.event_name == 'workflow_dispatch' }}
      uses: actions/upload-artifact@v3
      with:
        name: coverage
        path: ./dist/coverage
        retention-days: 1

