name: Test PHP
on:
  workflow_call:
    inputs:
      #-----------------------------------------------------------------------------------------------------------------
      # Usage
      #-----------------------------------------------------------------------------------------------------------------
      PHP_COMMAND:
        type: string
        required: false
        default: composer run test
      PHP_BUILD_COMMAND:
        type: string
        required: false
        default: composer run build:ci
      #-----------------------------------------------------------------------------------------------------------------
      # Common
      #-----------------------------------------------------------------------------------------------------------------
      WORKING_DIR:
        type: string
        required: false
        default: .
      #-----------------------------------------------------------------------------------------------------------------
      # Features
      #-----------------------------------------------------------------------------------------------------------------
      # No Features
      #-----------------------------------------------------------------------------------------------------------------
      # Platform
      #-----------------------------------------------------------------------------------------------------------------
      OS_VERSION:
        type: string
        required: false
        default: ubuntu-24.04
      PHP_VERSION:
        type: string
        required: false
        default: "8.4"
      #-----------------------------------------------------------------------------------------------------------------
      # Registry
      #-----------------------------------------------------------------------------------------------------------------
      # No PHP Registry
      #-----------------------------------------------------------------------------------------------------------------
      # Artifact
      #-----------------------------------------------------------------------------------------------------------------
      BUILD_ARTIFACT_NAME:
        type: string
        required: false
        default: build
      BUILD_ARTIFACT_PATH:
        type: string
        required: false
        default: build
      TEST_ARTIFACT_NAME:
        type: string
        required: false
        default: coverage
      TEST_ARTIFACT_PATH:
        type: string
        required: false
        default: dist/coverage
      TEST_ARTIFACT_RETENTION:
        type: string
        required: false
        default: "1"
    secrets: {}
      #-----------------------------------------------------------------------------------------------------------------
      # Registry
      #-----------------------------------------------------------------------------------------------------------------
      # No PHP Registry
jobs:
  #---------------------------------------------------------------------------------------------------------------------
  # Test
  #---------------------------------------------------------------------------------------------------------------------
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        php-version:
        - ${{ inputs.PHP_VERSION }}
        os:
        - ${{ inputs.OS_VERSION }}
    steps:
    #-------------------------------------------------------------------------------------------------------------------
    # Prepare Repository
    #-------------------------------------------------------------------------------------------------------------------
    - name: Prepare
      uses: actions/checkout@v4
    #-------------------------------------------------------------------------------------------------------------------
    # Download Artifact
    #-------------------------------------------------------------------------------------------------------------------
    - name: Download Build
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.BUILD_ARTIFACT_NAME }}
        path: ${{ inputs.BUILD_ARTIFACT_PATH }}
    #-------------------------------------------------------------------------------------------------------------------
    # Setup Platform
    #-------------------------------------------------------------------------------------------------------------------
    - name: Configure PHP
      uses: bayudwiyansatria/.github/actions/configure-php@master
      with:
        php-version: ${{ inputs.PHP_VERSION }}
    #-------------------------------------------------------------------------------------------------------------------
    # Installing Package
    #-------------------------------------------------------------------------------------------------------------------
    - name: Install PHP Packages
      run: >-
        composer
        --prefer-dist
        --no-interaction
        install 
      working-directory: ${{ inputs.WORKING_DIR }}
    #-------------------------------------------------------------------------------------------------------------------
    # Build Package
    #-------------------------------------------------------------------------------------------------------------------
    - name: Build PHP Packages
      run: ${{ inputs.PHP_BUILD_COMMAND }}
      working-directory: ${{ inputs.WORKING_DIR }}
    #-------------------------------------------------------------------------------------------------------------------
    # Run Unit Test
    #-------------------------------------------------------------------------------------------------------------------
    - name: Run Unit Test
      run: ${{ inputs.PHP_COMMAND }}
      working-directory: ${{ inputs.WORKING_DIR }}
    #-------------------------------------------------------------------------------------------------------------------
    # Upload Artifact
    #-------------------------------------------------------------------------------------------------------------------
    - name: Archive Coverage Result
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.TEST_ARTIFACT_NAME }}
        path: ${{ inputs.TEST_ARTIFACT_PATH }}
        retention-days: ${{ inputs.TEST_ARTIFACT_RETENTION }}
