name: Test Node
on:
  workflow_call:
    inputs:
      #---------------------------------------------------------------------------------------------------------------------
      # Platform
      #---------------------------------------------------------------------------------------------------------------------
      NODE_VERSION:
        type: string
        required: false
        default: "16"
      #---------------------------------------------------------------------------------------------------------------------
      # Registry
      #---------------------------------------------------------------------------------------------------------------------
      NPM_REGISTRY:
        type: string
        required: false
        default: https://npm.pkg.github.com
      #---------------------------------------------------------------------------------------------------------------------
      # Artifact
      #---------------------------------------------------------------------------------------------------------------------
      BUILD_ARTIFACT_NAME:
        type: string
        required: false
        default: lib
      BUILD_ARTIFACT_PATH:
        type: string
        required: false
        default: ./lib
      ARTIFACT_NAME:
        type: string
        required: false
        default: coverage
      ARTIFACT_PATH:
        type: string
        required: false
        default: ./dist/coverage
      ARTIFACT_RETENTION:
        type: string
        required: false
        default: "1"
    secrets:
      #---------------------------------------------------------------------------------------------------------------------
      # Registry
      #---------------------------------------------------------------------------------------------------------------------
      NPM_AUTH_TOKEN:
        required: true
      #---------------------------------------------------------------------------------------------------------------------
      # CodeQuality
      #---------------------------------------------------------------------------------------------------------------------
      CODECOV_TOKEN:
        required: true
jobs:
  #---------------------------------------------------------------------------------------------------------------------
  # Test
  #---------------------------------------------------------------------------------------------------------------------
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version:
        - ${{ inputs.NODE_VERSION }}
        os:
        - ubuntu-latest
    steps:
    # Prepare Repository
    - name: Prepare
      uses: actions/checkout@v3
    # Download Artifact
    - name: Download Lib
      uses: actions/download-artifact@v3
      with:
        name: ${{ inputs.BUILD_ARTIFACT_NAME }}
        path: ${{ inputs.BUILD_ARTIFACT_PATH }}
    # Setup Node
    - name: Set Up Node
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: ${{ inputs.NPM_REGISTRY }}
        cache: npm
        always-auth: true
        check-latest: false
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
    # Installing Package
    - name: Installing Node Packages
      run: npm ci
    # Run Test
    - name: Test
      run: npm run test --if-present
    - name: Coverage Result Analysis
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        directory: ${{ inputs.ARTIFACT_PATH }}
        files: clover.xml
        flags: unittests
        name: ${{ github.event.repository.name }}
        fail_ci_if_error: true
    # Only Upload If Workflow Called
    - name: Archive Coverage Result
      uses: actions/upload-artifact@v3
      with:
        name: ${{ inputs.ARTIFACT_NAME }}
        path: ${{ inputs.ARTIFACT_PATH }}
        retention-days: ${{ inputs.ARTIFACT_RETENTION }}